package com.cd.rems.dao;

import com.cd.rems.entity.TBuildingcarpark;
import java.util.List;

public interface TBuildingcarparkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buildingcarparkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    int insert(TBuildingcarpark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    TBuildingcarpark selectByPrimaryKey(Integer buildingcarparkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    List<TBuildingcarpark> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuildingcarpark record);
}