package com.cd.rems.dao;

import com.cd.rems.entity.TBuildinginfo;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TBuildinginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    int insert(TBuildinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    TBuildinginfo selectByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    List<TBuildinginfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuildinginfo record);
}