package com.cd.rems.dao;

import com.cd.rems.entity.TBuildingsale;
import java.util.List;

public interface TBuildingsaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buildingsaleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSale
     *
     * @mbg.generated
     */
    int insert(TBuildingsale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSale
     *
     * @mbg.generated
     */
    TBuildingsale selectByPrimaryKey(Integer buildingsaleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSale
     *
     * @mbg.generated
     */
    List<TBuildingsale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuildingsale record);
}