package com.cd.rems.dao;

import com.cd.rems.entity.TBuildingqualification;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TBuildingqualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buildingqualificationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    int insert(TBuildingqualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    TBuildingqualification selectByPrimaryKey(Integer buildingqualificationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    List<TBuildingqualification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuildingqualification record);
}