package com.cd.rems.dao;

import com.cd.rems.entity.TBuildinginfo;
import com.cd.rems.model.BuildingInfoVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TBuildinginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    int insert(TBuildinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    TBuildinginfo selectByPrimaryKey(Integer buildingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    List<TBuildinginfo> selectAll(@Param("info") BuildingInfoVo info);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuildinginfo record);

    List<TBuildinginfo> selectByPage(@Param("info") BuildingInfoVo record);
}