package com.cd.rems.dao;

import com.cd.rems.entity.TCarparknatureFile;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TCarparknatureFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkNature_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparknatureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkNature_file
     *
     * @mbg.generated
     */
    int insert(TCarparknatureFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkNature_file
     *
     * @mbg.generated
     */
    TCarparknatureFile selectByPrimaryKey(Integer carparknatureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkNature_file
     *
     * @mbg.generated
     */
    List<TCarparknatureFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkNature_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarparknatureFile record);
}