package com.cd.rems.dao;

import com.cd.rems.entity.TCarparksurveyinfo;
import java.util.List;

public interface TCarparksurveyinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparksurveyinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    int insert(TCarparksurveyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    TCarparksurveyinfo selectByPrimaryKey(Integer carparksurveyinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    List<TCarparksurveyinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarparksurveyinfo record);
}