package com.cd.rems.dao;

import com.cd.rems.entity.TCarparktype;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TCarparktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType
     *
     * @mbg.generated
     */
    int insert(TCarparktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType
     *
     * @mbg.generated
     */
    TCarparktype selectByPrimaryKey(Integer carparktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType
     *
     * @mbg.generated
     */
    List<TCarparktype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarparktype record);
}