package com.cd.rems.dao;

import com.cd.rems.entity.TCarpark;
import com.cd.rems.model.CarparkVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TCarparkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    int insert(TCarpark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    TCarpark selectByPrimaryKey(Integer carparkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    List<TCarpark> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarpark record);

    /**
     * 获取所有数量
     * @return
     */
    int selectCountAll();

    /**
     * 根据查询条件获取总数量
     * @param carparkVo
     * @return
     */
    int selectCountAllByCondition(@Param("carparkVo")CarparkVo carparkVo);

}