package com.cd.rems.dao;

import com.cd.rems.entity.TCarparkFile;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TCarparkFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparkfileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    int insert(TCarparkFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    TCarparkFile selectByPrimaryKey(Integer carparkfileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    List<TCarparkFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarparkFile record);
}