package com.cd.rems.dao;

import com.cd.rems.entity.TCarparktypeFile;
import java.util.List;

public interface TCarparktypeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    int insert(TCarparktypeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    TCarparktypeFile selectByPrimaryKey(Integer carparktypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    List<TCarparktypeFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCarparktypeFile record);
}