package com.cd.rems.dao;

import com.cd.rems.entity.TChargepattern;
import java.util.List;

public interface TChargepatternMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer chargepatternid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    int insert(TChargepattern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    TChargepattern selectByPrimaryKey(Integer chargepatternid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    List<TChargepattern> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TChargepattern record);
}