package com.cd.rems.dao;

import com.cd.rems.entity.TInternetaccess;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TInternetaccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer internetaccessid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    int insert(TInternetaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    TInternetaccess selectByPrimaryKey(Integer internetaccessid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    List<TInternetaccess> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInternetaccess record);
}