package com.cd.rems.dao;

import com.cd.rems.entity.TNetwork;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TNetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer networkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network
     *
     * @mbg.generated
     */
    int insert(TNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network
     *
     * @mbg.generated
     */
    TNetwork selectByPrimaryKey(Integer networkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network
     *
     * @mbg.generated
     */
    List<TNetwork> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_network
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TNetwork record);
}