package com.cd.rems.dao;

import com.cd.rems.entity.TParklotstatusFile;
import java.util.List;

public interface TParklotstatusFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parklotstatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    int insert(TParklotstatusFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    TParklotstatusFile selectByPrimaryKey(Integer parklotstatusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    List<TParklotstatusFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotstatusFile record);
}