package com.cd.rems.dao;

import com.cd.rems.entity.TParklot;
import java.util.List;

public interface TParklotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parklotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    int insert(TParklot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    TParklot selectByPrimaryKey(Integer parklotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    List<TParklot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklot record);
}