package com.cd.rems.dao;

import com.cd.rems.entity.TParklotFile;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklotFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carparkfileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_file
     *
     * @mbg.generated
     */
    int insert(TParklotFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_file
     *
     * @mbg.generated
     */
    TParklotFile selectByPrimaryKey(Integer carparkfileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_file
     *
     * @mbg.generated
     */
    List<TParklotFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotFile record);
}