package com.cd.rems.dao;

import com.cd.rems.entity.TParklotIncome;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklotIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_income
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_income
     *
     * @mbg.generated
     */
    int insert(TParklotIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_income
     *
     * @mbg.generated
     */
    TParklotIncome selectByPrimaryKey(Integer incomeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_income
     *
     * @mbg.generated
     */
    List<TParklotIncome> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_income
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotIncome record);
}