package com.cd.rems.dao;

import com.cd.rems.entity.TParklotLoan;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklotLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lotloanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    int insert(TParklotLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    TParklotLoan selectByPrimaryKey(Integer lotloanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    List<TParklotLoan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotLoan record);
}