package com.cd.rems.dao;

import com.cd.rems.entity.TParklotMortgage;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklotMortgageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mortgageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    int insert(TParklotMortgage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    TParklotMortgage selectByPrimaryKey(Integer mortgageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    List<TParklotMortgage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotMortgage record);
}