package com.cd.rems.dao;

import com.cd.rems.entity.TParklotLog;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklotLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lotlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    int insert(TParklotLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    TParklotLog selectByPrimaryKey(Integer lotlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    List<TParklotLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklotLog record);
}