package com.cd.rems.dao;

import com.cd.rems.entity.TParklottypeFile;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TParklottypeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parklottypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    int insert(TParklottypeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    TParklottypeFile selectByPrimaryKey(Integer parklottypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    List<TParklottypeFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TParklottypeFile record);
}