package com.cd.rems.dao;

import com.cd.rems.entity.TPaymode;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TPaymodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payMode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer paymodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payMode
     *
     * @mbg.generated
     */
    int insert(TPaymode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payMode
     *
     * @mbg.generated
     */
    TPaymode selectByPrimaryKey(Integer paymodeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payMode
     *
     * @mbg.generated
     */
    List<TPaymode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payMode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPaymode record);
}