package com.cd.rems.dao;

import com.cd.rems.entity.TRenttypeFile;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TRenttypeFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer renttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    int insert(TRenttypeFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    TRenttypeFile selectByPrimaryKey(Integer renttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    List<TRenttypeFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TRenttypeFile record);
}