package com.cd.rems.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TBuildinginfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.buildingName
     *
     * @mbg.generated
     */
    private String buildingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.buildingAddr
     *
     * @mbg.generated
     */
    private String buildingaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.nowTypeId
     *
     * @mbg.generated
     */
    private Integer nowtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.addTime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.developer
     *
     * @mbg.generated
     */
    private String developer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.propertyManager
     *
     * @mbg.generated
     */
    private String propertymanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.propertyManagerFee
     *
     * @mbg.generated
     */
    private BigDecimal propertymanagerfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.buildingNumber
     *
     * @mbg.generated
     */
    private Integer buildingnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.averagePrice
     *
     * @mbg.generated
     */
    private BigDecimal averageprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.saleDate
     *
     * @mbg.generated
     */
    private Date saledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.saleIssue
     *
     * @mbg.generated
     */
    private String saleissue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.deliveredDate
     *
     * @mbg.generated
     */
    private Date delivereddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.intputer
     *
     * @mbg.generated
     */
    private String intputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.contacts
     *
     * @mbg.generated
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.contactsTel
     *
     * @mbg.generated
     */
    private String contactstel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.inputDate
     *
     * @mbg.generated
     */
    private Date inputdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.totalArea
     *
     * @mbg.generated
     */
    private BigDecimal totalarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.areaRate
     *
     * @mbg.generated
     */
    private BigDecimal arearate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.carparkNumber
     *
     * @mbg.generated
     */
    private Integer carparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.carparkLayerNumber
     *
     * @mbg.generated
     */
    private Integer carparklayernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.carparkPrice
     *
     * @mbg.generated
     */
    private BigDecimal carparkprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.NTCarparkNumber
     *
     * @mbg.generated
     */
    private Integer ntcarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.carparkRate
     *
     * @mbg.generated
     */
    private BigDecimal carparkrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.upCarpark
     *
     * @mbg.generated
     */
    private Integer upcarpark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.downCarpark
     *
     * @mbg.generated
     */
    private Integer downcarpark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.carparkFee
     *
     * @mbg.generated
     */
    private BigDecimal carparkfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.upMaCarpark
     *
     * @mbg.generated
     */
    private Integer upmacarpark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.downMaCarpark
     *
     * @mbg.generated
     */
    private Integer downmacarpark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildinginfo.maFee
     *
     * @mbg.generated
     */
    private BigDecimal mafee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.buildingId
     *
     * @return the value of t_buildinginfo.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.buildingId
     *
     * @param buildingid the value for t_buildinginfo.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.buildingName
     *
     * @return the value of t_buildinginfo.buildingName
     *
     * @mbg.generated
     */
    public String getBuildingname() {
        return buildingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.buildingName
     *
     * @param buildingname the value for t_buildinginfo.buildingName
     *
     * @mbg.generated
     */
    public void setBuildingname(String buildingname) {
        this.buildingname = buildingname == null ? null : buildingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.buildingAddr
     *
     * @return the value of t_buildinginfo.buildingAddr
     *
     * @mbg.generated
     */
    public String getBuildingaddr() {
        return buildingaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.buildingAddr
     *
     * @param buildingaddr the value for t_buildinginfo.buildingAddr
     *
     * @mbg.generated
     */
    public void setBuildingaddr(String buildingaddr) {
        this.buildingaddr = buildingaddr == null ? null : buildingaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.nowTypeId
     *
     * @return the value of t_buildinginfo.nowTypeId
     *
     * @mbg.generated
     */
    public Integer getNowtypeid() {
        return nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.nowTypeId
     *
     * @param nowtypeid the value for t_buildinginfo.nowTypeId
     *
     * @mbg.generated
     */
    public void setNowtypeid(Integer nowtypeid) {
        this.nowtypeid = nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.addTime
     *
     * @return the value of t_buildinginfo.addTime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.addTime
     *
     * @param addtime the value for t_buildinginfo.addTime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.developer
     *
     * @return the value of t_buildinginfo.developer
     *
     * @mbg.generated
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.developer
     *
     * @param developer the value for t_buildinginfo.developer
     *
     * @mbg.generated
     */
    public void setDeveloper(String developer) {
        this.developer = developer == null ? null : developer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.propertyManager
     *
     * @return the value of t_buildinginfo.propertyManager
     *
     * @mbg.generated
     */
    public String getPropertymanager() {
        return propertymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.propertyManager
     *
     * @param propertymanager the value for t_buildinginfo.propertyManager
     *
     * @mbg.generated
     */
    public void setPropertymanager(String propertymanager) {
        this.propertymanager = propertymanager == null ? null : propertymanager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.propertyManagerFee
     *
     * @return the value of t_buildinginfo.propertyManagerFee
     *
     * @mbg.generated
     */
    public BigDecimal getPropertymanagerfee() {
        return propertymanagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.propertyManagerFee
     *
     * @param propertymanagerfee the value for t_buildinginfo.propertyManagerFee
     *
     * @mbg.generated
     */
    public void setPropertymanagerfee(BigDecimal propertymanagerfee) {
        this.propertymanagerfee = propertymanagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.buildingNumber
     *
     * @return the value of t_buildinginfo.buildingNumber
     *
     * @mbg.generated
     */
    public Integer getBuildingnumber() {
        return buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.buildingNumber
     *
     * @param buildingnumber the value for t_buildinginfo.buildingNumber
     *
     * @mbg.generated
     */
    public void setBuildingnumber(Integer buildingnumber) {
        this.buildingnumber = buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.averagePrice
     *
     * @return the value of t_buildinginfo.averagePrice
     *
     * @mbg.generated
     */
    public BigDecimal getAverageprice() {
        return averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.averagePrice
     *
     * @param averageprice the value for t_buildinginfo.averagePrice
     *
     * @mbg.generated
     */
    public void setAverageprice(BigDecimal averageprice) {
        this.averageprice = averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.saleDate
     *
     * @return the value of t_buildinginfo.saleDate
     *
     * @mbg.generated
     */
    public Date getSaledate() {
        return saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.saleDate
     *
     * @param saledate the value for t_buildinginfo.saleDate
     *
     * @mbg.generated
     */
    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.saleIssue
     *
     * @return the value of t_buildinginfo.saleIssue
     *
     * @mbg.generated
     */
    public String getSaleissue() {
        return saleissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.saleIssue
     *
     * @param saleissue the value for t_buildinginfo.saleIssue
     *
     * @mbg.generated
     */
    public void setSaleissue(String saleissue) {
        this.saleissue = saleissue == null ? null : saleissue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.deliveredDate
     *
     * @return the value of t_buildinginfo.deliveredDate
     *
     * @mbg.generated
     */
    public Date getDelivereddate() {
        return delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.deliveredDate
     *
     * @param delivereddate the value for t_buildinginfo.deliveredDate
     *
     * @mbg.generated
     */
    public void setDelivereddate(Date delivereddate) {
        this.delivereddate = delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.intputer
     *
     * @return the value of t_buildinginfo.intputer
     *
     * @mbg.generated
     */
    public String getIntputer() {
        return intputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.intputer
     *
     * @param intputer the value for t_buildinginfo.intputer
     *
     * @mbg.generated
     */
    public void setIntputer(String intputer) {
        this.intputer = intputer == null ? null : intputer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.contacts
     *
     * @return the value of t_buildinginfo.contacts
     *
     * @mbg.generated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.contacts
     *
     * @param contacts the value for t_buildinginfo.contacts
     *
     * @mbg.generated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.contactsTel
     *
     * @return the value of t_buildinginfo.contactsTel
     *
     * @mbg.generated
     */
    public String getContactstel() {
        return contactstel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.contactsTel
     *
     * @param contactstel the value for t_buildinginfo.contactsTel
     *
     * @mbg.generated
     */
    public void setContactstel(String contactstel) {
        this.contactstel = contactstel == null ? null : contactstel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.inputDate
     *
     * @return the value of t_buildinginfo.inputDate
     *
     * @mbg.generated
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.inputDate
     *
     * @param inputdate the value for t_buildinginfo.inputDate
     *
     * @mbg.generated
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.totalArea
     *
     * @return the value of t_buildinginfo.totalArea
     *
     * @mbg.generated
     */
    public BigDecimal getTotalarea() {
        return totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.totalArea
     *
     * @param totalarea the value for t_buildinginfo.totalArea
     *
     * @mbg.generated
     */
    public void setTotalarea(BigDecimal totalarea) {
        this.totalarea = totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.areaRate
     *
     * @return the value of t_buildinginfo.areaRate
     *
     * @mbg.generated
     */
    public BigDecimal getArearate() {
        return arearate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.areaRate
     *
     * @param arearate the value for t_buildinginfo.areaRate
     *
     * @mbg.generated
     */
    public void setArearate(BigDecimal arearate) {
        this.arearate = arearate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.carparkNumber
     *
     * @return the value of t_buildinginfo.carparkNumber
     *
     * @mbg.generated
     */
    public Integer getCarparknumber() {
        return carparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.carparkNumber
     *
     * @param carparknumber the value for t_buildinginfo.carparkNumber
     *
     * @mbg.generated
     */
    public void setCarparknumber(Integer carparknumber) {
        this.carparknumber = carparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.carparkLayerNumber
     *
     * @return the value of t_buildinginfo.carparkLayerNumber
     *
     * @mbg.generated
     */
    public Integer getCarparklayernumber() {
        return carparklayernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.carparkLayerNumber
     *
     * @param carparklayernumber the value for t_buildinginfo.carparkLayerNumber
     *
     * @mbg.generated
     */
    public void setCarparklayernumber(Integer carparklayernumber) {
        this.carparklayernumber = carparklayernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.carparkPrice
     *
     * @return the value of t_buildinginfo.carparkPrice
     *
     * @mbg.generated
     */
    public BigDecimal getCarparkprice() {
        return carparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.carparkPrice
     *
     * @param carparkprice the value for t_buildinginfo.carparkPrice
     *
     * @mbg.generated
     */
    public void setCarparkprice(BigDecimal carparkprice) {
        this.carparkprice = carparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.NTCarparkNumber
     *
     * @return the value of t_buildinginfo.NTCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getNtcarparknumber() {
        return ntcarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.NTCarparkNumber
     *
     * @param ntcarparknumber the value for t_buildinginfo.NTCarparkNumber
     *
     * @mbg.generated
     */
    public void setNtcarparknumber(Integer ntcarparknumber) {
        this.ntcarparknumber = ntcarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.carparkRate
     *
     * @return the value of t_buildinginfo.carparkRate
     *
     * @mbg.generated
     */
    public BigDecimal getCarparkrate() {
        return carparkrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.carparkRate
     *
     * @param carparkrate the value for t_buildinginfo.carparkRate
     *
     * @mbg.generated
     */
    public void setCarparkrate(BigDecimal carparkrate) {
        this.carparkrate = carparkrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.upCarpark
     *
     * @return the value of t_buildinginfo.upCarpark
     *
     * @mbg.generated
     */
    public Integer getUpcarpark() {
        return upcarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.upCarpark
     *
     * @param upcarpark the value for t_buildinginfo.upCarpark
     *
     * @mbg.generated
     */
    public void setUpcarpark(Integer upcarpark) {
        this.upcarpark = upcarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.downCarpark
     *
     * @return the value of t_buildinginfo.downCarpark
     *
     * @mbg.generated
     */
    public Integer getDowncarpark() {
        return downcarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.downCarpark
     *
     * @param downcarpark the value for t_buildinginfo.downCarpark
     *
     * @mbg.generated
     */
    public void setDowncarpark(Integer downcarpark) {
        this.downcarpark = downcarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.carparkFee
     *
     * @return the value of t_buildinginfo.carparkFee
     *
     * @mbg.generated
     */
    public BigDecimal getCarparkfee() {
        return carparkfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.carparkFee
     *
     * @param carparkfee the value for t_buildinginfo.carparkFee
     *
     * @mbg.generated
     */
    public void setCarparkfee(BigDecimal carparkfee) {
        this.carparkfee = carparkfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.upMaCarpark
     *
     * @return the value of t_buildinginfo.upMaCarpark
     *
     * @mbg.generated
     */
    public Integer getUpmacarpark() {
        return upmacarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.upMaCarpark
     *
     * @param upmacarpark the value for t_buildinginfo.upMaCarpark
     *
     * @mbg.generated
     */
    public void setUpmacarpark(Integer upmacarpark) {
        this.upmacarpark = upmacarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.downMaCarpark
     *
     * @return the value of t_buildinginfo.downMaCarpark
     *
     * @mbg.generated
     */
    public Integer getDownmacarpark() {
        return downmacarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.downMaCarpark
     *
     * @param downmacarpark the value for t_buildinginfo.downMaCarpark
     *
     * @mbg.generated
     */
    public void setDownmacarpark(Integer downmacarpark) {
        this.downmacarpark = downmacarpark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildinginfo.maFee
     *
     * @return the value of t_buildinginfo.maFee
     *
     * @mbg.generated
     */
    public BigDecimal getMafee() {
        return mafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildinginfo.maFee
     *
     * @param mafee the value for t_buildinginfo.maFee
     *
     * @mbg.generated
     */
    public void setMafee(BigDecimal mafee) {
        this.mafee = mafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildinginfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingid=").append(buildingid);
        sb.append(", buildingname=").append(buildingname);
        sb.append(", buildingaddr=").append(buildingaddr);
        sb.append(", nowtypeid=").append(nowtypeid);
        sb.append(", addtime=").append(addtime);
        sb.append(", developer=").append(developer);
        sb.append(", propertymanager=").append(propertymanager);
        sb.append(", propertymanagerfee=").append(propertymanagerfee);
        sb.append(", buildingnumber=").append(buildingnumber);
        sb.append(", averageprice=").append(averageprice);
        sb.append(", saledate=").append(saledate);
        sb.append(", saleissue=").append(saleissue);
        sb.append(", delivereddate=").append(delivereddate);
        sb.append(", intputer=").append(intputer);
        sb.append(", contacts=").append(contacts);
        sb.append(", contactstel=").append(contactstel);
        sb.append(", inputdate=").append(inputdate);
        sb.append(", totalarea=").append(totalarea);
        sb.append(", arearate=").append(arearate);
        sb.append(", carparknumber=").append(carparknumber);
        sb.append(", carparklayernumber=").append(carparklayernumber);
        sb.append(", carparkprice=").append(carparkprice);
        sb.append(", ntcarparknumber=").append(ntcarparknumber);
        sb.append(", carparkrate=").append(carparkrate);
        sb.append(", upcarpark=").append(upcarpark);
        sb.append(", downcarpark=").append(downcarpark);
        sb.append(", carparkfee=").append(carparkfee);
        sb.append(", upmacarpark=").append(upmacarpark);
        sb.append(", downmacarpark=").append(downmacarpark);
        sb.append(", mafee=").append(mafee);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}