package com.cd.rems.entity;

import java.io.Serializable;

public class TBuildingcarpark implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.buildingCarparkId
     *
     * @mbg.generated
     */
    private Integer buildingcarparkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.carparkName
     *
     * @mbg.generated
     */
    private String carparkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.carparkNumber
     *
     * @mbg.generated
     */
    private Integer carparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.fieldsCarparkNumber
     *
     * @mbg.generated
     */
    private Integer fieldscarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.fieldsCarparkPrice
     *
     * @mbg.generated
     */
    private Long fieldscarparkprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementOneCarparkNumber
     *
     * @mbg.generated
     */
    private Integer beasementonecarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementOneCarparkPrice
     *
     * @mbg.generated
     */
    private Long beasementonecarparkprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementTwoCarparkNumber
     *
     * @mbg.generated
     */
    private Integer beasementtwocarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementTwoCarparkPrice
     *
     * @mbg.generated
     */
    private Long beasementtwocarparkprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementThreeCarparkNumber
     *
     * @mbg.generated
     */
    private Integer beasementthreecarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementThreeCarparkPrice
     *
     * @mbg.generated
     */
    private Long beasementthreecarparkprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementFourCarparkNumber
     *
     * @mbg.generated
     */
    private Integer beasementfourcarparknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingCarpark.beasementFourCarparkPrice
     *
     * @mbg.generated
     */
    private Long beasementfourcarparkprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.buildingCarparkId
     *
     * @return the value of t_buildingCarpark.buildingCarparkId
     *
     * @mbg.generated
     */
    public Integer getBuildingcarparkid() {
        return buildingcarparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.buildingCarparkId
     *
     * @param buildingcarparkid the value for t_buildingCarpark.buildingCarparkId
     *
     * @mbg.generated
     */
    public void setBuildingcarparkid(Integer buildingcarparkid) {
        this.buildingcarparkid = buildingcarparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.carparkName
     *
     * @return the value of t_buildingCarpark.carparkName
     *
     * @mbg.generated
     */
    public String getCarparkname() {
        return carparkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.carparkName
     *
     * @param carparkname the value for t_buildingCarpark.carparkName
     *
     * @mbg.generated
     */
    public void setCarparkname(String carparkname) {
        this.carparkname = carparkname == null ? null : carparkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.carparkNumber
     *
     * @return the value of t_buildingCarpark.carparkNumber
     *
     * @mbg.generated
     */
    public Integer getCarparknumber() {
        return carparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.carparkNumber
     *
     * @param carparknumber the value for t_buildingCarpark.carparkNumber
     *
     * @mbg.generated
     */
    public void setCarparknumber(Integer carparknumber) {
        this.carparknumber = carparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.fieldsCarparkNumber
     *
     * @return the value of t_buildingCarpark.fieldsCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getFieldscarparknumber() {
        return fieldscarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.fieldsCarparkNumber
     *
     * @param fieldscarparknumber the value for t_buildingCarpark.fieldsCarparkNumber
     *
     * @mbg.generated
     */
    public void setFieldscarparknumber(Integer fieldscarparknumber) {
        this.fieldscarparknumber = fieldscarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.fieldsCarparkPrice
     *
     * @return the value of t_buildingCarpark.fieldsCarparkPrice
     *
     * @mbg.generated
     */
    public Long getFieldscarparkprice() {
        return fieldscarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.fieldsCarparkPrice
     *
     * @param fieldscarparkprice the value for t_buildingCarpark.fieldsCarparkPrice
     *
     * @mbg.generated
     */
    public void setFieldscarparkprice(Long fieldscarparkprice) {
        this.fieldscarparkprice = fieldscarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementOneCarparkNumber
     *
     * @return the value of t_buildingCarpark.beasementOneCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getBeasementonecarparknumber() {
        return beasementonecarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementOneCarparkNumber
     *
     * @param beasementonecarparknumber the value for t_buildingCarpark.beasementOneCarparkNumber
     *
     * @mbg.generated
     */
    public void setBeasementonecarparknumber(Integer beasementonecarparknumber) {
        this.beasementonecarparknumber = beasementonecarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementOneCarparkPrice
     *
     * @return the value of t_buildingCarpark.beasementOneCarparkPrice
     *
     * @mbg.generated
     */
    public Long getBeasementonecarparkprice() {
        return beasementonecarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementOneCarparkPrice
     *
     * @param beasementonecarparkprice the value for t_buildingCarpark.beasementOneCarparkPrice
     *
     * @mbg.generated
     */
    public void setBeasementonecarparkprice(Long beasementonecarparkprice) {
        this.beasementonecarparkprice = beasementonecarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.buildingId
     *
     * @return the value of t_buildingCarpark.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.buildingId
     *
     * @param buildingid the value for t_buildingCarpark.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementTwoCarparkNumber
     *
     * @return the value of t_buildingCarpark.beasementTwoCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getBeasementtwocarparknumber() {
        return beasementtwocarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementTwoCarparkNumber
     *
     * @param beasementtwocarparknumber the value for t_buildingCarpark.beasementTwoCarparkNumber
     *
     * @mbg.generated
     */
    public void setBeasementtwocarparknumber(Integer beasementtwocarparknumber) {
        this.beasementtwocarparknumber = beasementtwocarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementTwoCarparkPrice
     *
     * @return the value of t_buildingCarpark.beasementTwoCarparkPrice
     *
     * @mbg.generated
     */
    public Long getBeasementtwocarparkprice() {
        return beasementtwocarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementTwoCarparkPrice
     *
     * @param beasementtwocarparkprice the value for t_buildingCarpark.beasementTwoCarparkPrice
     *
     * @mbg.generated
     */
    public void setBeasementtwocarparkprice(Long beasementtwocarparkprice) {
        this.beasementtwocarparkprice = beasementtwocarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementThreeCarparkNumber
     *
     * @return the value of t_buildingCarpark.beasementThreeCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getBeasementthreecarparknumber() {
        return beasementthreecarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementThreeCarparkNumber
     *
     * @param beasementthreecarparknumber the value for t_buildingCarpark.beasementThreeCarparkNumber
     *
     * @mbg.generated
     */
    public void setBeasementthreecarparknumber(Integer beasementthreecarparknumber) {
        this.beasementthreecarparknumber = beasementthreecarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementThreeCarparkPrice
     *
     * @return the value of t_buildingCarpark.beasementThreeCarparkPrice
     *
     * @mbg.generated
     */
    public Long getBeasementthreecarparkprice() {
        return beasementthreecarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementThreeCarparkPrice
     *
     * @param beasementthreecarparkprice the value for t_buildingCarpark.beasementThreeCarparkPrice
     *
     * @mbg.generated
     */
    public void setBeasementthreecarparkprice(Long beasementthreecarparkprice) {
        this.beasementthreecarparkprice = beasementthreecarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementFourCarparkNumber
     *
     * @return the value of t_buildingCarpark.beasementFourCarparkNumber
     *
     * @mbg.generated
     */
    public Integer getBeasementfourcarparknumber() {
        return beasementfourcarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementFourCarparkNumber
     *
     * @param beasementfourcarparknumber the value for t_buildingCarpark.beasementFourCarparkNumber
     *
     * @mbg.generated
     */
    public void setBeasementfourcarparknumber(Integer beasementfourcarparknumber) {
        this.beasementfourcarparknumber = beasementfourcarparknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingCarpark.beasementFourCarparkPrice
     *
     * @return the value of t_buildingCarpark.beasementFourCarparkPrice
     *
     * @mbg.generated
     */
    public Long getBeasementfourcarparkprice() {
        return beasementfourcarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingCarpark.beasementFourCarparkPrice
     *
     * @param beasementfourcarparkprice the value for t_buildingCarpark.beasementFourCarparkPrice
     *
     * @mbg.generated
     */
    public void setBeasementfourcarparkprice(Long beasementfourcarparkprice) {
        this.beasementfourcarparkprice = beasementfourcarparkprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingCarpark
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingcarparkid=").append(buildingcarparkid);
        sb.append(", carparkname=").append(carparkname);
        sb.append(", carparknumber=").append(carparknumber);
        sb.append(", fieldscarparknumber=").append(fieldscarparknumber);
        sb.append(", fieldscarparkprice=").append(fieldscarparkprice);
        sb.append(", beasementonecarparknumber=").append(beasementonecarparknumber);
        sb.append(", beasementonecarparkprice=").append(beasementonecarparkprice);
        sb.append(", buildingid=").append(buildingid);
        sb.append(", beasementtwocarparknumber=").append(beasementtwocarparknumber);
        sb.append(", beasementtwocarparkprice=").append(beasementtwocarparkprice);
        sb.append(", beasementthreecarparknumber=").append(beasementthreecarparknumber);
        sb.append(", beasementthreecarparkprice=").append(beasementthreecarparkprice);
        sb.append(", beasementfourcarparknumber=").append(beasementfourcarparknumber);
        sb.append(", beasementfourcarparkprice=").append(beasementfourcarparkprice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}