package com.cd.rems.entity;

import java.io.Serializable;

public class TBuildingsaleinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.buildingSaleInfoId
     *
     * @mbg.generated
     */
    private Integer buildingsaleinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.totalSaledNumber
     *
     * @mbg.generated
     */
    private Integer totalsalednumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.buildingAvgPrice
     *
     * @mbg.generated
     */
    private Long buildingavgprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.saledParklotNumber
     *
     * @mbg.generated
     */
    private Integer saledparklotnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.saledParklotPrice
     *
     * @mbg.generated
     */
    private Long saledparklotprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.occupancyRate
     *
     * @mbg.generated
     */
    private Integer occupancyrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.deliveryRate
     *
     * @mbg.generated
     */
    private Integer deliveryrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.saledShopsNumber
     *
     * @mbg.generated
     */
    private Integer saledshopsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.saledShopsArea
     *
     * @mbg.generated
     */
    private Long saledshopsarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.shopsPrice
     *
     * @mbg.generated
     */
    private Long shopsprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.shopsRent
     *
     * @mbg.generated
     */
    private Long shopsrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingSaleInfo.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buildingSaleInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.buildingSaleInfoId
     *
     * @return the value of t_buildingSaleInfo.buildingSaleInfoId
     *
     * @mbg.generated
     */
    public Integer getBuildingsaleinfoid() {
        return buildingsaleinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.buildingSaleInfoId
     *
     * @param buildingsaleinfoid the value for t_buildingSaleInfo.buildingSaleInfoId
     *
     * @mbg.generated
     */
    public void setBuildingsaleinfoid(Integer buildingsaleinfoid) {
        this.buildingsaleinfoid = buildingsaleinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.totalSaledNumber
     *
     * @return the value of t_buildingSaleInfo.totalSaledNumber
     *
     * @mbg.generated
     */
    public Integer getTotalsalednumber() {
        return totalsalednumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.totalSaledNumber
     *
     * @param totalsalednumber the value for t_buildingSaleInfo.totalSaledNumber
     *
     * @mbg.generated
     */
    public void setTotalsalednumber(Integer totalsalednumber) {
        this.totalsalednumber = totalsalednumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.buildingAvgPrice
     *
     * @return the value of t_buildingSaleInfo.buildingAvgPrice
     *
     * @mbg.generated
     */
    public Long getBuildingavgprice() {
        return buildingavgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.buildingAvgPrice
     *
     * @param buildingavgprice the value for t_buildingSaleInfo.buildingAvgPrice
     *
     * @mbg.generated
     */
    public void setBuildingavgprice(Long buildingavgprice) {
        this.buildingavgprice = buildingavgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.saledParklotNumber
     *
     * @return the value of t_buildingSaleInfo.saledParklotNumber
     *
     * @mbg.generated
     */
    public Integer getSaledparklotnumber() {
        return saledparklotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.saledParklotNumber
     *
     * @param saledparklotnumber the value for t_buildingSaleInfo.saledParklotNumber
     *
     * @mbg.generated
     */
    public void setSaledparklotnumber(Integer saledparklotnumber) {
        this.saledparklotnumber = saledparklotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.saledParklotPrice
     *
     * @return the value of t_buildingSaleInfo.saledParklotPrice
     *
     * @mbg.generated
     */
    public Long getSaledparklotprice() {
        return saledparklotprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.saledParklotPrice
     *
     * @param saledparklotprice the value for t_buildingSaleInfo.saledParklotPrice
     *
     * @mbg.generated
     */
    public void setSaledparklotprice(Long saledparklotprice) {
        this.saledparklotprice = saledparklotprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.occupancyRate
     *
     * @return the value of t_buildingSaleInfo.occupancyRate
     *
     * @mbg.generated
     */
    public Integer getOccupancyrate() {
        return occupancyrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.occupancyRate
     *
     * @param occupancyrate the value for t_buildingSaleInfo.occupancyRate
     *
     * @mbg.generated
     */
    public void setOccupancyrate(Integer occupancyrate) {
        this.occupancyrate = occupancyrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.deliveryRate
     *
     * @return the value of t_buildingSaleInfo.deliveryRate
     *
     * @mbg.generated
     */
    public Integer getDeliveryrate() {
        return deliveryrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.deliveryRate
     *
     * @param deliveryrate the value for t_buildingSaleInfo.deliveryRate
     *
     * @mbg.generated
     */
    public void setDeliveryrate(Integer deliveryrate) {
        this.deliveryrate = deliveryrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.saledShopsNumber
     *
     * @return the value of t_buildingSaleInfo.saledShopsNumber
     *
     * @mbg.generated
     */
    public Integer getSaledshopsnumber() {
        return saledshopsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.saledShopsNumber
     *
     * @param saledshopsnumber the value for t_buildingSaleInfo.saledShopsNumber
     *
     * @mbg.generated
     */
    public void setSaledshopsnumber(Integer saledshopsnumber) {
        this.saledshopsnumber = saledshopsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.saledShopsArea
     *
     * @return the value of t_buildingSaleInfo.saledShopsArea
     *
     * @mbg.generated
     */
    public Long getSaledshopsarea() {
        return saledshopsarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.saledShopsArea
     *
     * @param saledshopsarea the value for t_buildingSaleInfo.saledShopsArea
     *
     * @mbg.generated
     */
    public void setSaledshopsarea(Long saledshopsarea) {
        this.saledshopsarea = saledshopsarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.shopsPrice
     *
     * @return the value of t_buildingSaleInfo.shopsPrice
     *
     * @mbg.generated
     */
    public Long getShopsprice() {
        return shopsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.shopsPrice
     *
     * @param shopsprice the value for t_buildingSaleInfo.shopsPrice
     *
     * @mbg.generated
     */
    public void setShopsprice(Long shopsprice) {
        this.shopsprice = shopsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.shopsRent
     *
     * @return the value of t_buildingSaleInfo.shopsRent
     *
     * @mbg.generated
     */
    public Long getShopsrent() {
        return shopsrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.shopsRent
     *
     * @param shopsrent the value for t_buildingSaleInfo.shopsRent
     *
     * @mbg.generated
     */
    public void setShopsrent(Long shopsrent) {
        this.shopsrent = shopsrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingSaleInfo.buildingId
     *
     * @return the value of t_buildingSaleInfo.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingSaleInfo.buildingId
     *
     * @param buildingid the value for t_buildingSaleInfo.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingSaleInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingsaleinfoid=").append(buildingsaleinfoid);
        sb.append(", totalsalednumber=").append(totalsalednumber);
        sb.append(", buildingavgprice=").append(buildingavgprice);
        sb.append(", saledparklotnumber=").append(saledparklotnumber);
        sb.append(", saledparklotprice=").append(saledparklotprice);
        sb.append(", occupancyrate=").append(occupancyrate);
        sb.append(", deliveryrate=").append(deliveryrate);
        sb.append(", saledshopsnumber=").append(saledshopsnumber);
        sb.append(", saledshopsarea=").append(saledshopsarea);
        sb.append(", shopsprice=").append(shopsprice);
        sb.append(", shopsrent=").append(shopsrent);
        sb.append(", buildingid=").append(buildingid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}