package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TBuildinginfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.buildingName
     *
     * @mbg.generated
     */
    private String buildingname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.buildingAddr
     *
     * @mbg.generated
     */
    private String buildingaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.nowTypeId
     *
     * @mbg.generated
     */
    private Integer nowtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.addTime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.developer
     *
     * @mbg.generated
     */
    private String developer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.propertyManager
     *
     * @mbg.generated
     */
    private String propertymanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.propertyManagerFee
     *
     * @mbg.generated
     */
    private Long propertymanagerfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.buildingNumber
     *
     * @mbg.generated
     */
    private Integer buildingnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.averagePrice
     *
     * @mbg.generated
     */
    private Long averageprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.saleDate
     *
     * @mbg.generated
     */
    private Date saledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.saleIssue
     *
     * @mbg.generated
     */
    private String saleissue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.deliveredDate
     *
     * @mbg.generated
     */
    private Date delivereddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.intputer
     *
     * @mbg.generated
     */
    private String intputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.contacts
     *
     * @mbg.generated
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.contactsTel
     *
     * @mbg.generated
     */
    private String contactstel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.inputDate
     *
     * @mbg.generated
     */
    private Date inputdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.totalArea
     *
     * @mbg.generated
     */
    private Long totalarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingInfo.areaRate
     *
     * @mbg.generated
     */
    private Long arearate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.buildingId
     *
     * @return the value of t_buildingInfo.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.buildingId
     *
     * @param buildingid the value for t_buildingInfo.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.buildingName
     *
     * @return the value of t_buildingInfo.buildingName
     *
     * @mbg.generated
     */
    public String getBuildingname() {
        return buildingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.buildingName
     *
     * @param buildingname the value for t_buildingInfo.buildingName
     *
     * @mbg.generated
     */
    public void setBuildingname(String buildingname) {
        this.buildingname = buildingname == null ? null : buildingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.buildingAddr
     *
     * @return the value of t_buildingInfo.buildingAddr
     *
     * @mbg.generated
     */
    public String getBuildingaddr() {
        return buildingaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.buildingAddr
     *
     * @param buildingaddr the value for t_buildingInfo.buildingAddr
     *
     * @mbg.generated
     */
    public void setBuildingaddr(String buildingaddr) {
        this.buildingaddr = buildingaddr == null ? null : buildingaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.nowTypeId
     *
     * @return the value of t_buildingInfo.nowTypeId
     *
     * @mbg.generated
     */
    public Integer getNowtypeid() {
        return nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.nowTypeId
     *
     * @param nowtypeid the value for t_buildingInfo.nowTypeId
     *
     * @mbg.generated
     */
    public void setNowtypeid(Integer nowtypeid) {
        this.nowtypeid = nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.addTime
     *
     * @return the value of t_buildingInfo.addTime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.addTime
     *
     * @param addtime the value for t_buildingInfo.addTime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.developer
     *
     * @return the value of t_buildingInfo.developer
     *
     * @mbg.generated
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.developer
     *
     * @param developer the value for t_buildingInfo.developer
     *
     * @mbg.generated
     */
    public void setDeveloper(String developer) {
        this.developer = developer == null ? null : developer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.propertyManager
     *
     * @return the value of t_buildingInfo.propertyManager
     *
     * @mbg.generated
     */
    public String getPropertymanager() {
        return propertymanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.propertyManager
     *
     * @param propertymanager the value for t_buildingInfo.propertyManager
     *
     * @mbg.generated
     */
    public void setPropertymanager(String propertymanager) {
        this.propertymanager = propertymanager == null ? null : propertymanager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.propertyManagerFee
     *
     * @return the value of t_buildingInfo.propertyManagerFee
     *
     * @mbg.generated
     */
    public Long getPropertymanagerfee() {
        return propertymanagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.propertyManagerFee
     *
     * @param propertymanagerfee the value for t_buildingInfo.propertyManagerFee
     *
     * @mbg.generated
     */
    public void setPropertymanagerfee(Long propertymanagerfee) {
        this.propertymanagerfee = propertymanagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.buildingNumber
     *
     * @return the value of t_buildingInfo.buildingNumber
     *
     * @mbg.generated
     */
    public Integer getBuildingnumber() {
        return buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.buildingNumber
     *
     * @param buildingnumber the value for t_buildingInfo.buildingNumber
     *
     * @mbg.generated
     */
    public void setBuildingnumber(Integer buildingnumber) {
        this.buildingnumber = buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.averagePrice
     *
     * @return the value of t_buildingInfo.averagePrice
     *
     * @mbg.generated
     */
    public Long getAverageprice() {
        return averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.averagePrice
     *
     * @param averageprice the value for t_buildingInfo.averagePrice
     *
     * @mbg.generated
     */
    public void setAverageprice(Long averageprice) {
        this.averageprice = averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.saleDate
     *
     * @return the value of t_buildingInfo.saleDate
     *
     * @mbg.generated
     */
    public Date getSaledate() {
        return saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.saleDate
     *
     * @param saledate the value for t_buildingInfo.saleDate
     *
     * @mbg.generated
     */
    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.saleIssue
     *
     * @return the value of t_buildingInfo.saleIssue
     *
     * @mbg.generated
     */
    public String getSaleissue() {
        return saleissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.saleIssue
     *
     * @param saleissue the value for t_buildingInfo.saleIssue
     *
     * @mbg.generated
     */
    public void setSaleissue(String saleissue) {
        this.saleissue = saleissue == null ? null : saleissue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.deliveredDate
     *
     * @return the value of t_buildingInfo.deliveredDate
     *
     * @mbg.generated
     */
    public Date getDelivereddate() {
        return delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.deliveredDate
     *
     * @param delivereddate the value for t_buildingInfo.deliveredDate
     *
     * @mbg.generated
     */
    public void setDelivereddate(Date delivereddate) {
        this.delivereddate = delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.intputer
     *
     * @return the value of t_buildingInfo.intputer
     *
     * @mbg.generated
     */
    public String getIntputer() {
        return intputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.intputer
     *
     * @param intputer the value for t_buildingInfo.intputer
     *
     * @mbg.generated
     */
    public void setIntputer(String intputer) {
        this.intputer = intputer == null ? null : intputer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.contacts
     *
     * @return the value of t_buildingInfo.contacts
     *
     * @mbg.generated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.contacts
     *
     * @param contacts the value for t_buildingInfo.contacts
     *
     * @mbg.generated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.contactsTel
     *
     * @return the value of t_buildingInfo.contactsTel
     *
     * @mbg.generated
     */
    public String getContactstel() {
        return contactstel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.contactsTel
     *
     * @param contactstel the value for t_buildingInfo.contactsTel
     *
     * @mbg.generated
     */
    public void setContactstel(String contactstel) {
        this.contactstel = contactstel == null ? null : contactstel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.inputDate
     *
     * @return the value of t_buildingInfo.inputDate
     *
     * @mbg.generated
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.inputDate
     *
     * @param inputdate the value for t_buildingInfo.inputDate
     *
     * @mbg.generated
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.totalArea
     *
     * @return the value of t_buildingInfo.totalArea
     *
     * @mbg.generated
     */
    public Long getTotalarea() {
        return totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.totalArea
     *
     * @param totalarea the value for t_buildingInfo.totalArea
     *
     * @mbg.generated
     */
    public void setTotalarea(Long totalarea) {
        this.totalarea = totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingInfo.areaRate
     *
     * @return the value of t_buildingInfo.areaRate
     *
     * @mbg.generated
     */
    public Long getArearate() {
        return arearate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingInfo.areaRate
     *
     * @param arearate the value for t_buildingInfo.areaRate
     *
     * @mbg.generated
     */
    public void setArearate(Long arearate) {
        this.arearate = arearate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingid=").append(buildingid);
        sb.append(", buildingname=").append(buildingname);
        sb.append(", buildingaddr=").append(buildingaddr);
        sb.append(", nowtypeid=").append(nowtypeid);
        sb.append(", addtime=").append(addtime);
        sb.append(", developer=").append(developer);
        sb.append(", propertymanager=").append(propertymanager);
        sb.append(", propertymanagerfee=").append(propertymanagerfee);
        sb.append(", buildingnumber=").append(buildingnumber);
        sb.append(", averageprice=").append(averageprice);
        sb.append(", saledate=").append(saledate);
        sb.append(", saleissue=").append(saleissue);
        sb.append(", delivereddate=").append(delivereddate);
        sb.append(", intputer=").append(intputer);
        sb.append(", contacts=").append(contacts);
        sb.append(", contactstel=").append(contactstel);
        sb.append(", inputdate=").append(inputdate);
        sb.append(", totalarea=").append(totalarea);
        sb.append(", arearate=").append(arearate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}