package com.cd.rems.entity;

import java.io.Serializable;

public class TBuildingqualification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.buildingQualificationId
     *
     * @mbg.generated
     */
    private Integer buildingqualificationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.SLOUCIds
     *
     * @mbg.generated
     */
    private String sloucids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.landUsePermitIds
     *
     * @mbg.generated
     */
    private String landusepermitids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.buildingPermitIds
     *
     * @mbg.generated
     */
    private String buildingpermitids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.builingLicenseIds
     *
     * @mbg.generated
     */
    private String builinglicenseids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.salesLicenseIds
     *
     * @mbg.generated
     */
    private String saleslicenseids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buildingQualification.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.buildingQualificationId
     *
     * @return the value of t_buildingQualification.buildingQualificationId
     *
     * @mbg.generated
     */
    public Integer getBuildingqualificationid() {
        return buildingqualificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.buildingQualificationId
     *
     * @param buildingqualificationid the value for t_buildingQualification.buildingQualificationId
     *
     * @mbg.generated
     */
    public void setBuildingqualificationid(Integer buildingqualificationid) {
        this.buildingqualificationid = buildingqualificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.SLOUCIds
     *
     * @return the value of t_buildingQualification.SLOUCIds
     *
     * @mbg.generated
     */
    public String getSloucids() {
        return sloucids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.SLOUCIds
     *
     * @param sloucids the value for t_buildingQualification.SLOUCIds
     *
     * @mbg.generated
     */
    public void setSloucids(String sloucids) {
        this.sloucids = sloucids == null ? null : sloucids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.landUsePermitIds
     *
     * @return the value of t_buildingQualification.landUsePermitIds
     *
     * @mbg.generated
     */
    public String getLandusepermitids() {
        return landusepermitids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.landUsePermitIds
     *
     * @param landusepermitids the value for t_buildingQualification.landUsePermitIds
     *
     * @mbg.generated
     */
    public void setLandusepermitids(String landusepermitids) {
        this.landusepermitids = landusepermitids == null ? null : landusepermitids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.buildingPermitIds
     *
     * @return the value of t_buildingQualification.buildingPermitIds
     *
     * @mbg.generated
     */
    public String getBuildingpermitids() {
        return buildingpermitids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.buildingPermitIds
     *
     * @param buildingpermitids the value for t_buildingQualification.buildingPermitIds
     *
     * @mbg.generated
     */
    public void setBuildingpermitids(String buildingpermitids) {
        this.buildingpermitids = buildingpermitids == null ? null : buildingpermitids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.builingLicenseIds
     *
     * @return the value of t_buildingQualification.builingLicenseIds
     *
     * @mbg.generated
     */
    public String getBuilinglicenseids() {
        return builinglicenseids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.builingLicenseIds
     *
     * @param builinglicenseids the value for t_buildingQualification.builingLicenseIds
     *
     * @mbg.generated
     */
    public void setBuilinglicenseids(String builinglicenseids) {
        this.builinglicenseids = builinglicenseids == null ? null : builinglicenseids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.salesLicenseIds
     *
     * @return the value of t_buildingQualification.salesLicenseIds
     *
     * @mbg.generated
     */
    public String getSaleslicenseids() {
        return saleslicenseids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.salesLicenseIds
     *
     * @param saleslicenseids the value for t_buildingQualification.salesLicenseIds
     *
     * @mbg.generated
     */
    public void setSaleslicenseids(String saleslicenseids) {
        this.saleslicenseids = saleslicenseids == null ? null : saleslicenseids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buildingQualification.buildingId
     *
     * @return the value of t_buildingQualification.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buildingQualification.buildingId
     *
     * @param buildingid the value for t_buildingQualification.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buildingQualification
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingqualificationid=").append(buildingqualificationid);
        sb.append(", sloucids=").append(sloucids);
        sb.append(", landusepermitids=").append(landusepermitids);
        sb.append(", buildingpermitids=").append(buildingpermitids);
        sb.append(", builinglicenseids=").append(builinglicenseids);
        sb.append(", saleslicenseids=").append(saleslicenseids);
        sb.append(", buildingid=").append(buildingid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}