package com.cd.rems.entity;

import java.io.Serializable;

public class TCarparkFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark_file.carparkfileId
     *
     * @mbg.generated
     */
    private Integer carparkfileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark_file.fileType
     *
     * @mbg.generated
     */
    private String filetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark_file.filePath
     *
     * @mbg.generated
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark_file.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark_file.carparkfileId
     *
     * @return the value of t_carpark_file.carparkfileId
     *
     * @mbg.generated
     */
    public Integer getCarparkfileid() {
        return carparkfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark_file.carparkfileId
     *
     * @param carparkfileid the value for t_carpark_file.carparkfileId
     *
     * @mbg.generated
     */
    public void setCarparkfileid(Integer carparkfileid) {
        this.carparkfileid = carparkfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark_file.fileType
     *
     * @return the value of t_carpark_file.fileType
     *
     * @mbg.generated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark_file.fileType
     *
     * @param filetype the value for t_carpark_file.fileType
     *
     * @mbg.generated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark_file.filePath
     *
     * @return the value of t_carpark_file.filePath
     *
     * @mbg.generated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark_file.filePath
     *
     * @param filepath the value for t_carpark_file.filePath
     *
     * @mbg.generated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark_file.carparkId
     *
     * @return the value of t_carpark_file.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark_file.carparkId
     *
     * @param carparkid the value for t_carpark_file.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carparkfileid=").append(carparkfileid);
        sb.append(", filetype=").append(filetype);
        sb.append(", filepath=").append(filepath);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}