package com.cd.rems.entity;

import java.io.Serializable;

public class TCarparksurveyinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    private Integer carparksurveyinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carparkName
     *
     * @mbg.generated
     */
    private String carparkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carparkAddr
     *
     * @mbg.generated
     */
    private String carparkaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.pickupPeople
     *
     * @mbg.generated
     */
    private String pickuppeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.pickupTel
     *
     * @mbg.generated
     */
    private String pickuptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.备注
     *
     * @mbg.generated
     */
    private String 备注;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carparkProId
     *
     * @mbg.generated
     */
    private Integer carparkproid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carparkTypeId
     *
     * @mbg.generated
     */
    private Integer carparktypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.carplotTypeId
     *
     * @mbg.generated
     */
    private Integer carplottypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.intputNumber
     *
     * @mbg.generated
     */
    private Integer intputnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.outputNumber
     *
     * @mbg.generated
     */
    private Integer outputnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.mixOutputNumber
     *
     * @mbg.generated
     */
    private Integer mixoutputnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.fixCarplotNumber
     *
     * @mbg.generated
     */
    private Integer fixcarplotnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkSurveyInfo.enclosureIds
     *
     * @mbg.generated
     */
    private Integer enclosureids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carparkSurveyInfoId
     *
     * @return the value of t_carparkSurveyInfo.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public Integer getCarparksurveyinfoid() {
        return carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carparkSurveyInfoId
     *
     * @param carparksurveyinfoid the value for t_carparkSurveyInfo.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public void setCarparksurveyinfoid(Integer carparksurveyinfoid) {
        this.carparksurveyinfoid = carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carparkName
     *
     * @return the value of t_carparkSurveyInfo.carparkName
     *
     * @mbg.generated
     */
    public String getCarparkname() {
        return carparkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carparkName
     *
     * @param carparkname the value for t_carparkSurveyInfo.carparkName
     *
     * @mbg.generated
     */
    public void setCarparkname(String carparkname) {
        this.carparkname = carparkname == null ? null : carparkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carparkAddr
     *
     * @return the value of t_carparkSurveyInfo.carparkAddr
     *
     * @mbg.generated
     */
    public String getCarparkaddr() {
        return carparkaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carparkAddr
     *
     * @param carparkaddr the value for t_carparkSurveyInfo.carparkAddr
     *
     * @mbg.generated
     */
    public void setCarparkaddr(String carparkaddr) {
        this.carparkaddr = carparkaddr == null ? null : carparkaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.pickupPeople
     *
     * @return the value of t_carparkSurveyInfo.pickupPeople
     *
     * @mbg.generated
     */
    public String getPickuppeople() {
        return pickuppeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.pickupPeople
     *
     * @param pickuppeople the value for t_carparkSurveyInfo.pickupPeople
     *
     * @mbg.generated
     */
    public void setPickuppeople(String pickuppeople) {
        this.pickuppeople = pickuppeople == null ? null : pickuppeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.pickupTel
     *
     * @return the value of t_carparkSurveyInfo.pickupTel
     *
     * @mbg.generated
     */
    public String getPickuptel() {
        return pickuptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.pickupTel
     *
     * @param pickuptel the value for t_carparkSurveyInfo.pickupTel
     *
     * @mbg.generated
     */
    public void setPickuptel(String pickuptel) {
        this.pickuptel = pickuptel == null ? null : pickuptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.备注
     *
     * @return the value of t_carparkSurveyInfo.备注
     *
     * @mbg.generated
     */
    public String get备注() {
        return 备注;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.备注
     *
     * @param 备注 the value for t_carparkSurveyInfo.备注
     *
     * @mbg.generated
     */
    public void set备注(String 备注) {
        this.备注 = 备注 == null ? null : 备注.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carparkProId
     *
     * @return the value of t_carparkSurveyInfo.carparkProId
     *
     * @mbg.generated
     */
    public Integer getCarparkproid() {
        return carparkproid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carparkProId
     *
     * @param carparkproid the value for t_carparkSurveyInfo.carparkProId
     *
     * @mbg.generated
     */
    public void setCarparkproid(Integer carparkproid) {
        this.carparkproid = carparkproid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carparkTypeId
     *
     * @return the value of t_carparkSurveyInfo.carparkTypeId
     *
     * @mbg.generated
     */
    public Integer getCarparktypeid() {
        return carparktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carparkTypeId
     *
     * @param carparktypeid the value for t_carparkSurveyInfo.carparkTypeId
     *
     * @mbg.generated
     */
    public void setCarparktypeid(Integer carparktypeid) {
        this.carparktypeid = carparktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.carplotTypeId
     *
     * @return the value of t_carparkSurveyInfo.carplotTypeId
     *
     * @mbg.generated
     */
    public Integer getCarplottypeid() {
        return carplottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.carplotTypeId
     *
     * @param carplottypeid the value for t_carparkSurveyInfo.carplotTypeId
     *
     * @mbg.generated
     */
    public void setCarplottypeid(Integer carplottypeid) {
        this.carplottypeid = carplottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.intputNumber
     *
     * @return the value of t_carparkSurveyInfo.intputNumber
     *
     * @mbg.generated
     */
    public Integer getIntputnumber() {
        return intputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.intputNumber
     *
     * @param intputnumber the value for t_carparkSurveyInfo.intputNumber
     *
     * @mbg.generated
     */
    public void setIntputnumber(Integer intputnumber) {
        this.intputnumber = intputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.outputNumber
     *
     * @return the value of t_carparkSurveyInfo.outputNumber
     *
     * @mbg.generated
     */
    public Integer getOutputnumber() {
        return outputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.outputNumber
     *
     * @param outputnumber the value for t_carparkSurveyInfo.outputNumber
     *
     * @mbg.generated
     */
    public void setOutputnumber(Integer outputnumber) {
        this.outputnumber = outputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.mixOutputNumber
     *
     * @return the value of t_carparkSurveyInfo.mixOutputNumber
     *
     * @mbg.generated
     */
    public Integer getMixoutputnumber() {
        return mixoutputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.mixOutputNumber
     *
     * @param mixoutputnumber the value for t_carparkSurveyInfo.mixOutputNumber
     *
     * @mbg.generated
     */
    public void setMixoutputnumber(Integer mixoutputnumber) {
        this.mixoutputnumber = mixoutputnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.fixCarplotNumber
     *
     * @return the value of t_carparkSurveyInfo.fixCarplotNumber
     *
     * @mbg.generated
     */
    public Integer getFixcarplotnumber() {
        return fixcarplotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.fixCarplotNumber
     *
     * @param fixcarplotnumber the value for t_carparkSurveyInfo.fixCarplotNumber
     *
     * @mbg.generated
     */
    public void setFixcarplotnumber(Integer fixcarplotnumber) {
        this.fixcarplotnumber = fixcarplotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkSurveyInfo.enclosureIds
     *
     * @return the value of t_carparkSurveyInfo.enclosureIds
     *
     * @mbg.generated
     */
    public Integer getEnclosureids() {
        return enclosureids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkSurveyInfo.enclosureIds
     *
     * @param enclosureids the value for t_carparkSurveyInfo.enclosureIds
     *
     * @mbg.generated
     */
    public void setEnclosureids(Integer enclosureids) {
        this.enclosureids = enclosureids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkSurveyInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carparksurveyinfoid=").append(carparksurveyinfoid);
        sb.append(", carparkname=").append(carparkname);
        sb.append(", carparkaddr=").append(carparkaddr);
        sb.append(", pickuppeople=").append(pickuppeople);
        sb.append(", pickuptel=").append(pickuptel);
        sb.append(", 备注=").append(备注);
        sb.append(", carparkproid=").append(carparkproid);
        sb.append(", carparktypeid=").append(carparktypeid);
        sb.append(", carplottypeid=").append(carplottypeid);
        sb.append(", intputnumber=").append(intputnumber);
        sb.append(", outputnumber=").append(outputnumber);
        sb.append(", mixoutputnumber=").append(mixoutputnumber);
        sb.append(", fixcarplotnumber=").append(fixcarplotnumber);
        sb.append(", enclosureids=").append(enclosureids);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}