package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TCarpark implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkName
     *
     * @mbg.generated
     */
    private String carparkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkAddress
     *
     * @mbg.generated
     */
    private String carparkaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.entryUser
     *
     * @mbg.generated
     */
    private String entryuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.entryTime
     *
     * @mbg.generated
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.developers
     *
     * @mbg.generated
     */
    private String developers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.management
     *
     * @mbg.generated
     */
    private String management;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.propert
     *
     * @mbg.generated
     */
    private String propert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.equipment
     *
     * @mbg.generated
     */
    private String equipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkNature
     *
     * @mbg.generated
     */
    private Integer carparknature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkType
     *
     * @mbg.generated
     */
    private Integer carparktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.propertyYears
     *
     * @mbg.generated
     */
    private Integer propertyyears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.loanYears
     *
     * @mbg.generated
     */
    private Integer loanyears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkRank
     *
     * @mbg.generated
     */
    private Integer carparkrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkTotal
     *
     * @mbg.generated
     */
    private Integer carparktotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.carparkTotalLoan
     *
     * @mbg.generated
     */
    private Integer carparktotalloan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carpark.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkId
     *
     * @return the value of t_carpark.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkId
     *
     * @param carparkid the value for t_carpark.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkName
     *
     * @return the value of t_carpark.carparkName
     *
     * @mbg.generated
     */
    public String getCarparkname() {
        return carparkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkName
     *
     * @param carparkname the value for t_carpark.carparkName
     *
     * @mbg.generated
     */
    public void setCarparkname(String carparkname) {
        this.carparkname = carparkname == null ? null : carparkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkAddress
     *
     * @return the value of t_carpark.carparkAddress
     *
     * @mbg.generated
     */
    public String getCarparkaddress() {
        return carparkaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkAddress
     *
     * @param carparkaddress the value for t_carpark.carparkAddress
     *
     * @mbg.generated
     */
    public void setCarparkaddress(String carparkaddress) {
        this.carparkaddress = carparkaddress == null ? null : carparkaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.entryUser
     *
     * @return the value of t_carpark.entryUser
     *
     * @mbg.generated
     */
    public String getEntryuser() {
        return entryuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.entryUser
     *
     * @param entryuser the value for t_carpark.entryUser
     *
     * @mbg.generated
     */
    public void setEntryuser(String entryuser) {
        this.entryuser = entryuser == null ? null : entryuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.entryTime
     *
     * @return the value of t_carpark.entryTime
     *
     * @mbg.generated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.entryTime
     *
     * @param entrytime the value for t_carpark.entryTime
     *
     * @mbg.generated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.developers
     *
     * @return the value of t_carpark.developers
     *
     * @mbg.generated
     */
    public String getDevelopers() {
        return developers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.developers
     *
     * @param developers the value for t_carpark.developers
     *
     * @mbg.generated
     */
    public void setDevelopers(String developers) {
        this.developers = developers == null ? null : developers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.management
     *
     * @return the value of t_carpark.management
     *
     * @mbg.generated
     */
    public String getManagement() {
        return management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.management
     *
     * @param management the value for t_carpark.management
     *
     * @mbg.generated
     */
    public void setManagement(String management) {
        this.management = management == null ? null : management.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.operator
     *
     * @return the value of t_carpark.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.operator
     *
     * @param operator the value for t_carpark.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.propert
     *
     * @return the value of t_carpark.propert
     *
     * @mbg.generated
     */
    public String getPropert() {
        return propert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.propert
     *
     * @param propert the value for t_carpark.propert
     *
     * @mbg.generated
     */
    public void setPropert(String propert) {
        this.propert = propert == null ? null : propert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.equipment
     *
     * @return the value of t_carpark.equipment
     *
     * @mbg.generated
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.equipment
     *
     * @param equipment the value for t_carpark.equipment
     *
     * @mbg.generated
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment == null ? null : equipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkNature
     *
     * @return the value of t_carpark.carparkNature
     *
     * @mbg.generated
     */
    public Integer getCarparknature() {
        return carparknature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkNature
     *
     * @param carparknature the value for t_carpark.carparkNature
     *
     * @mbg.generated
     */
    public void setCarparknature(Integer carparknature) {
        this.carparknature = carparknature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkType
     *
     * @return the value of t_carpark.carparkType
     *
     * @mbg.generated
     */
    public Integer getCarparktype() {
        return carparktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkType
     *
     * @param carparktype the value for t_carpark.carparkType
     *
     * @mbg.generated
     */
    public void setCarparktype(Integer carparktype) {
        this.carparktype = carparktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.propertyYears
     *
     * @return the value of t_carpark.propertyYears
     *
     * @mbg.generated
     */
    public Integer getPropertyyears() {
        return propertyyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.propertyYears
     *
     * @param propertyyears the value for t_carpark.propertyYears
     *
     * @mbg.generated
     */
    public void setPropertyyears(Integer propertyyears) {
        this.propertyyears = propertyyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.loanYears
     *
     * @return the value of t_carpark.loanYears
     *
     * @mbg.generated
     */
    public Integer getLoanyears() {
        return loanyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.loanYears
     *
     * @param loanyears the value for t_carpark.loanYears
     *
     * @mbg.generated
     */
    public void setLoanyears(Integer loanyears) {
        this.loanyears = loanyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkRank
     *
     * @return the value of t_carpark.carparkRank
     *
     * @mbg.generated
     */
    public Integer getCarparkrank() {
        return carparkrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkRank
     *
     * @param carparkrank the value for t_carpark.carparkRank
     *
     * @mbg.generated
     */
    public void setCarparkrank(Integer carparkrank) {
        this.carparkrank = carparkrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkTotal
     *
     * @return the value of t_carpark.carparkTotal
     *
     * @mbg.generated
     */
    public Integer getCarparktotal() {
        return carparktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkTotal
     *
     * @param carparktotal the value for t_carpark.carparkTotal
     *
     * @mbg.generated
     */
    public void setCarparktotal(Integer carparktotal) {
        this.carparktotal = carparktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.carparkTotalLoan
     *
     * @return the value of t_carpark.carparkTotalLoan
     *
     * @mbg.generated
     */
    public Integer getCarparktotalloan() {
        return carparktotalloan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.carparkTotalLoan
     *
     * @param carparktotalloan the value for t_carpark.carparkTotalLoan
     *
     * @mbg.generated
     */
    public void setCarparktotalloan(Integer carparktotalloan) {
        this.carparktotalloan = carparktotalloan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carpark.buildingId
     *
     * @return the value of t_carpark.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carpark.buildingId
     *
     * @param buildingid the value for t_carpark.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carpark
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carparkid=").append(carparkid);
        sb.append(", carparkname=").append(carparkname);
        sb.append(", carparkaddress=").append(carparkaddress);
        sb.append(", entryuser=").append(entryuser);
        sb.append(", entrytime=").append(entrytime);
        sb.append(", developers=").append(developers);
        sb.append(", management=").append(management);
        sb.append(", operator=").append(operator);
        sb.append(", propert=").append(propert);
        sb.append(", equipment=").append(equipment);
        sb.append(", carparknature=").append(carparknature);
        sb.append(", carparktype=").append(carparktype);
        sb.append(", propertyyears=").append(propertyyears);
        sb.append(", loanyears=").append(loanyears);
        sb.append(", carparkrank=").append(carparkrank);
        sb.append(", carparktotal=").append(carparktotal);
        sb.append(", carparktotalloan=").append(carparktotalloan);
        sb.append(", buildingid=").append(buildingid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}