package com.cd.rems.entity;

import java.io.Serializable;

public class TCarparkpro implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkPro.carparkProId
     *
     * @mbg.generated
     */
    private Integer carparkproid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkPro.carparkPro
     *
     * @mbg.generated
     */
    private String carparkpro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkPro.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkPro.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    private Integer carparksurveyinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carparkPro
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkPro.carparkProId
     *
     * @return the value of t_carparkPro.carparkProId
     *
     * @mbg.generated
     */
    public Integer getCarparkproid() {
        return carparkproid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkPro.carparkProId
     *
     * @param carparkproid the value for t_carparkPro.carparkProId
     *
     * @mbg.generated
     */
    public void setCarparkproid(Integer carparkproid) {
        this.carparkproid = carparkproid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkPro.carparkPro
     *
     * @return the value of t_carparkPro.carparkPro
     *
     * @mbg.generated
     */
    public String getCarparkpro() {
        return carparkpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkPro.carparkPro
     *
     * @param carparkpro the value for t_carparkPro.carparkPro
     *
     * @mbg.generated
     */
    public void setCarparkpro(String carparkpro) {
        this.carparkpro = carparkpro == null ? null : carparkpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkPro.isSelected
     *
     * @return the value of t_carparkPro.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkPro.isSelected
     *
     * @param isselected the value for t_carparkPro.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkPro.carparkSurveyInfoId
     *
     * @return the value of t_carparkPro.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public Integer getCarparksurveyinfoid() {
        return carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkPro.carparkSurveyInfoId
     *
     * @param carparksurveyinfoid the value for t_carparkPro.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public void setCarparksurveyinfoid(Integer carparksurveyinfoid) {
        this.carparksurveyinfoid = carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkPro
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carparkproid=").append(carparkproid);
        sb.append(", carparkpro=").append(carparkpro);
        sb.append(", isselected=").append(isselected);
        sb.append(", carparksurveyinfoid=").append(carparksurveyinfoid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}