package com.cd.rems.entity;

import java.io.Serializable;

public class TCarparktypeFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkType_file.carparkTypeId
     *
     * @mbg.generated
     */
    private Integer carparktypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkType_file.carparkTypeName
     *
     * @mbg.generated
     */
    private String carparktypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carparkType_file.carparkType
     *
     * @mbg.generated
     */
    private Integer carparktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkType_file.carparkTypeId
     *
     * @return the value of t_carparkType_file.carparkTypeId
     *
     * @mbg.generated
     */
    public Integer getCarparktypeid() {
        return carparktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkType_file.carparkTypeId
     *
     * @param carparktypeid the value for t_carparkType_file.carparkTypeId
     *
     * @mbg.generated
     */
    public void setCarparktypeid(Integer carparktypeid) {
        this.carparktypeid = carparktypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkType_file.carparkTypeName
     *
     * @return the value of t_carparkType_file.carparkTypeName
     *
     * @mbg.generated
     */
    public String getCarparktypename() {
        return carparktypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkType_file.carparkTypeName
     *
     * @param carparktypename the value for t_carparkType_file.carparkTypeName
     *
     * @mbg.generated
     */
    public void setCarparktypename(String carparktypename) {
        this.carparktypename = carparktypename == null ? null : carparktypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carparkType_file.carparkType
     *
     * @return the value of t_carparkType_file.carparkType
     *
     * @mbg.generated
     */
    public Integer getCarparktype() {
        return carparktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carparkType_file.carparkType
     *
     * @param carparktype the value for t_carparkType_file.carparkType
     *
     * @mbg.generated
     */
    public void setCarparktype(Integer carparktype) {
        this.carparktype = carparktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carparkType_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carparktypeid=").append(carparktypeid);
        sb.append(", carparktypename=").append(carparktypename);
        sb.append(", carparktype=").append(carparktype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}