package com.cd.rems.entity;

import java.io.Serializable;

public class TCarplottype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carplotType.carplotTypeId
     *
     * @mbg.generated
     */
    private Integer carplottypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carplotType.carplotType
     *
     * @mbg.generated
     */
    private String carplottype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carplotType.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    private Integer carparksurveyinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carplotType.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_carplotType
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carplotType.carplotTypeId
     *
     * @return the value of t_carplotType.carplotTypeId
     *
     * @mbg.generated
     */
    public Integer getCarplottypeid() {
        return carplottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carplotType.carplotTypeId
     *
     * @param carplottypeid the value for t_carplotType.carplotTypeId
     *
     * @mbg.generated
     */
    public void setCarplottypeid(Integer carplottypeid) {
        this.carplottypeid = carplottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carplotType.carplotType
     *
     * @return the value of t_carplotType.carplotType
     *
     * @mbg.generated
     */
    public String getCarplottype() {
        return carplottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carplotType.carplotType
     *
     * @param carplottype the value for t_carplotType.carplotType
     *
     * @mbg.generated
     */
    public void setCarplottype(String carplottype) {
        this.carplottype = carplottype == null ? null : carplottype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carplotType.carparkSurveyInfoId
     *
     * @return the value of t_carplotType.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public Integer getCarparksurveyinfoid() {
        return carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carplotType.carparkSurveyInfoId
     *
     * @param carparksurveyinfoid the value for t_carplotType.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public void setCarparksurveyinfoid(Integer carparksurveyinfoid) {
        this.carparksurveyinfoid = carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carplotType.isSelected
     *
     * @return the value of t_carplotType.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carplotType.isSelected
     *
     * @param isselected the value for t_carplotType.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carplotType
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carplottypeid=").append(carplottypeid);
        sb.append(", carplottype=").append(carplottype);
        sb.append(", carparksurveyinfoid=").append(carparksurveyinfoid);
        sb.append(", isselected=").append(isselected);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}