package com.cd.rems.entity;

import java.io.Serializable;

public class TChargepattern implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.chargePatternId
     *
     * @mbg.generated
     */
    private Integer chargepatternid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.chargeTypeId
     *
     * @mbg.generated
     */
    private Integer chargetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.chargePattern
     *
     * @mbg.generated
     */
    private String chargepattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.chargeId
     *
     * @mbg.generated
     */
    private Integer chargeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.payModeId
     *
     * @mbg.generated
     */
    private Integer paymodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.otherCharge
     *
     * @mbg.generated
     */
    private String othercharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.eleModeId
     *
     * @mbg.generated
     */
    private Integer elemodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.discount
     *
     * @mbg.generated
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chargePattern.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    private Integer carparksurveyinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.chargePatternId
     *
     * @return the value of t_chargePattern.chargePatternId
     *
     * @mbg.generated
     */
    public Integer getChargepatternid() {
        return chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.chargePatternId
     *
     * @param chargepatternid the value for t_chargePattern.chargePatternId
     *
     * @mbg.generated
     */
    public void setChargepatternid(Integer chargepatternid) {
        this.chargepatternid = chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.chargeTypeId
     *
     * @return the value of t_chargePattern.chargeTypeId
     *
     * @mbg.generated
     */
    public Integer getChargetypeid() {
        return chargetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.chargeTypeId
     *
     * @param chargetypeid the value for t_chargePattern.chargeTypeId
     *
     * @mbg.generated
     */
    public void setChargetypeid(Integer chargetypeid) {
        this.chargetypeid = chargetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.chargePattern
     *
     * @return the value of t_chargePattern.chargePattern
     *
     * @mbg.generated
     */
    public String getChargepattern() {
        return chargepattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.chargePattern
     *
     * @param chargepattern the value for t_chargePattern.chargePattern
     *
     * @mbg.generated
     */
    public void setChargepattern(String chargepattern) {
        this.chargepattern = chargepattern == null ? null : chargepattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.chargeId
     *
     * @return the value of t_chargePattern.chargeId
     *
     * @mbg.generated
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.chargeId
     *
     * @param chargeid the value for t_chargePattern.chargeId
     *
     * @mbg.generated
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.payModeId
     *
     * @return the value of t_chargePattern.payModeId
     *
     * @mbg.generated
     */
    public Integer getPaymodeid() {
        return paymodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.payModeId
     *
     * @param paymodeid the value for t_chargePattern.payModeId
     *
     * @mbg.generated
     */
    public void setPaymodeid(Integer paymodeid) {
        this.paymodeid = paymodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.otherCharge
     *
     * @return the value of t_chargePattern.otherCharge
     *
     * @mbg.generated
     */
    public String getOthercharge() {
        return othercharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.otherCharge
     *
     * @param othercharge the value for t_chargePattern.otherCharge
     *
     * @mbg.generated
     */
    public void setOthercharge(String othercharge) {
        this.othercharge = othercharge == null ? null : othercharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.eleModeId
     *
     * @return the value of t_chargePattern.eleModeId
     *
     * @mbg.generated
     */
    public Integer getElemodeid() {
        return elemodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.eleModeId
     *
     * @param elemodeid the value for t_chargePattern.eleModeId
     *
     * @mbg.generated
     */
    public void setElemodeid(Integer elemodeid) {
        this.elemodeid = elemodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.discount
     *
     * @return the value of t_chargePattern.discount
     *
     * @mbg.generated
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.discount
     *
     * @param discount the value for t_chargePattern.discount
     *
     * @mbg.generated
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chargePattern.carparkSurveyInfoId
     *
     * @return the value of t_chargePattern.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public Integer getCarparksurveyinfoid() {
        return carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chargePattern.carparkSurveyInfoId
     *
     * @param carparksurveyinfoid the value for t_chargePattern.carparkSurveyInfoId
     *
     * @mbg.generated
     */
    public void setCarparksurveyinfoid(Integer carparksurveyinfoid) {
        this.carparksurveyinfoid = carparksurveyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chargePattern
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chargepatternid=").append(chargepatternid);
        sb.append(", chargetypeid=").append(chargetypeid);
        sb.append(", chargepattern=").append(chargepattern);
        sb.append(", chargeid=").append(chargeid);
        sb.append(", paymodeid=").append(paymodeid);
        sb.append(", othercharge=").append(othercharge);
        sb.append(", elemodeid=").append(elemodeid);
        sb.append(", discount=").append(discount);
        sb.append(", carparksurveyinfoid=").append(carparksurveyinfoid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}