package com.cd.rems.entity;

import java.io.Serializable;

public class TCharge implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge.chargeId
     *
     * @mbg.generated
     */
    private Integer chargeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge.chargeName
     *
     * @mbg.generated
     */
    private String chargename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_charge.chargePatternId
     *
     * @mbg.generated
     */
    private Integer chargepatternid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_charge
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge.chargeId
     *
     * @return the value of t_charge.chargeId
     *
     * @mbg.generated
     */
    public Integer getChargeid() {
        return chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge.chargeId
     *
     * @param chargeid the value for t_charge.chargeId
     *
     * @mbg.generated
     */
    public void setChargeid(Integer chargeid) {
        this.chargeid = chargeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge.chargeName
     *
     * @return the value of t_charge.chargeName
     *
     * @mbg.generated
     */
    public String getChargename() {
        return chargename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge.chargeName
     *
     * @param chargename the value for t_charge.chargeName
     *
     * @mbg.generated
     */
    public void setChargename(String chargename) {
        this.chargename = chargename == null ? null : chargename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge.isSelected
     *
     * @return the value of t_charge.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge.isSelected
     *
     * @param isselected the value for t_charge.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_charge.chargePatternId
     *
     * @return the value of t_charge.chargePatternId
     *
     * @mbg.generated
     */
    public Integer getChargepatternid() {
        return chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_charge.chargePatternId
     *
     * @param chargepatternid the value for t_charge.chargePatternId
     *
     * @mbg.generated
     */
    public void setChargepatternid(Integer chargepatternid) {
        this.chargepatternid = chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", chargeid=").append(chargeid);
        sb.append(", chargename=").append(chargename);
        sb.append(", isselected=").append(isselected);
        sb.append(", chargepatternid=").append(chargepatternid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}