package com.cd.rems.entity;

import java.io.Serializable;

public class TElemode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eleMode.eleModeId
     *
     * @mbg.generated
     */
    private Integer elemodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eleMode.eleMode
     *
     * @mbg.generated
     */
    private String elemode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eleMode.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eleMode.chargePatternId
     *
     * @mbg.generated
     */
    private Integer chargepatternid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_eleMode
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eleMode.eleModeId
     *
     * @return the value of t_eleMode.eleModeId
     *
     * @mbg.generated
     */
    public Integer getElemodeid() {
        return elemodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eleMode.eleModeId
     *
     * @param elemodeid the value for t_eleMode.eleModeId
     *
     * @mbg.generated
     */
    public void setElemodeid(Integer elemodeid) {
        this.elemodeid = elemodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eleMode.eleMode
     *
     * @return the value of t_eleMode.eleMode
     *
     * @mbg.generated
     */
    public String getElemode() {
        return elemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eleMode.eleMode
     *
     * @param elemode the value for t_eleMode.eleMode
     *
     * @mbg.generated
     */
    public void setElemode(String elemode) {
        this.elemode = elemode == null ? null : elemode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eleMode.isSelected
     *
     * @return the value of t_eleMode.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eleMode.isSelected
     *
     * @param isselected the value for t_eleMode.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eleMode.chargePatternId
     *
     * @return the value of t_eleMode.chargePatternId
     *
     * @mbg.generated
     */
    public Integer getChargepatternid() {
        return chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eleMode.chargePatternId
     *
     * @param chargepatternid the value for t_eleMode.chargePatternId
     *
     * @mbg.generated
     */
    public void setChargepatternid(Integer chargepatternid) {
        this.chargepatternid = chargepatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eleMode
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", elemodeid=").append(elemodeid);
        sb.append(", elemode=").append(elemode);
        sb.append(", isselected=").append(isselected);
        sb.append(", chargepatternid=").append(chargepatternid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}