package com.cd.rems.entity;

import java.io.Serializable;

public class TEnclosure implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enclosure.enclosureId
     *
     * @mbg.generated
     */
    private Integer enclosureid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enclosure.enclosurePhoto
     *
     * @mbg.generated
     */
    private String enclosurephoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enclosure.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enclosure.enclosureAddr
     *
     * @mbg.generated
     */
    private String enclosureaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_enclosure
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enclosure.enclosureId
     *
     * @return the value of t_enclosure.enclosureId
     *
     * @mbg.generated
     */
    public Integer getEnclosureid() {
        return enclosureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enclosure.enclosureId
     *
     * @param enclosureid the value for t_enclosure.enclosureId
     *
     * @mbg.generated
     */
    public void setEnclosureid(Integer enclosureid) {
        this.enclosureid = enclosureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enclosure.enclosurePhoto
     *
     * @return the value of t_enclosure.enclosurePhoto
     *
     * @mbg.generated
     */
    public String getEnclosurephoto() {
        return enclosurephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enclosure.enclosurePhoto
     *
     * @param enclosurephoto the value for t_enclosure.enclosurePhoto
     *
     * @mbg.generated
     */
    public void setEnclosurephoto(String enclosurephoto) {
        this.enclosurephoto = enclosurephoto == null ? null : enclosurephoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enclosure.remark
     *
     * @return the value of t_enclosure.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enclosure.remark
     *
     * @param remark the value for t_enclosure.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enclosure.enclosureAddr
     *
     * @return the value of t_enclosure.enclosureAddr
     *
     * @mbg.generated
     */
    public String getEnclosureaddr() {
        return enclosureaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enclosure.enclosureAddr
     *
     * @param enclosureaddr the value for t_enclosure.enclosureAddr
     *
     * @mbg.generated
     */
    public void setEnclosureaddr(String enclosureaddr) {
        this.enclosureaddr = enclosureaddr == null ? null : enclosureaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enclosure
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", enclosureid=").append(enclosureid);
        sb.append(", enclosurephoto=").append(enclosurephoto);
        sb.append(", remark=").append(remark);
        sb.append(", enclosureaddr=").append(enclosureaddr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}