package com.cd.rems.entity;

import java.io.Serializable;

public class TInternetaccess implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internetAccess.internetAccessId
     *
     * @mbg.generated
     */
    private Integer internetaccessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internetAccess.internetAccess
     *
     * @mbg.generated
     */
    private String internetaccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internetAccess.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internetAccess.carparkDeviceId
     *
     * @mbg.generated
     */
    private Integer carparkdeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internetAccess.internetAccessId
     *
     * @return the value of t_internetAccess.internetAccessId
     *
     * @mbg.generated
     */
    public Integer getInternetaccessid() {
        return internetaccessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internetAccess.internetAccessId
     *
     * @param internetaccessid the value for t_internetAccess.internetAccessId
     *
     * @mbg.generated
     */
    public void setInternetaccessid(Integer internetaccessid) {
        this.internetaccessid = internetaccessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internetAccess.internetAccess
     *
     * @return the value of t_internetAccess.internetAccess
     *
     * @mbg.generated
     */
    public String getInternetaccess() {
        return internetaccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internetAccess.internetAccess
     *
     * @param internetaccess the value for t_internetAccess.internetAccess
     *
     * @mbg.generated
     */
    public void setInternetaccess(String internetaccess) {
        this.internetaccess = internetaccess == null ? null : internetaccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internetAccess.isSelected
     *
     * @return the value of t_internetAccess.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internetAccess.isSelected
     *
     * @param isselected the value for t_internetAccess.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internetAccess.carparkDeviceId
     *
     * @return the value of t_internetAccess.carparkDeviceId
     *
     * @mbg.generated
     */
    public Integer getCarparkdeviceid() {
        return carparkdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internetAccess.carparkDeviceId
     *
     * @param carparkdeviceid the value for t_internetAccess.carparkDeviceId
     *
     * @mbg.generated
     */
    public void setCarparkdeviceid(Integer carparkdeviceid) {
        this.carparkdeviceid = carparkdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internetAccess
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", internetaccessid=").append(internetaccessid);
        sb.append(", internetaccess=").append(internetaccess);
        sb.append(", isselected=").append(isselected);
        sb.append(", carparkdeviceid=").append(carparkdeviceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}