package com.cd.rems.entity;

import java.io.Serializable;

public class TNav implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navId
     *
     * @mbg.generated
     */
    private Integer navid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.cId
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.pId
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navType
     *
     * @mbg.generated
     */
    private Short navtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navTitle
     *
     * @mbg.generated
     */
    private String navtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navUrl
     *
     * @mbg.generated
     */
    private String navurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navNum
     *
     * @mbg.generated
     */
    private Integer navnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navLevel
     *
     * @mbg.generated
     */
    private Integer navlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.navImg
     *
     * @mbg.generated
     */
    private String navimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.isVisible
     *
     * @mbg.generated
     */
    private Boolean isvisible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nav.permissionTag
     *
     * @mbg.generated
     */
    private String permissiontag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nav
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navId
     *
     * @return the value of t_nav.navId
     *
     * @mbg.generated
     */
    public Integer getNavid() {
        return navid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navId
     *
     * @param navid the value for t_nav.navId
     *
     * @mbg.generated
     */
    public void setNavid(Integer navid) {
        this.navid = navid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.cId
     *
     * @return the value of t_nav.cId
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.cId
     *
     * @param cid the value for t_nav.cId
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.pId
     *
     * @return the value of t_nav.pId
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.pId
     *
     * @param pid the value for t_nav.pId
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navType
     *
     * @return the value of t_nav.navType
     *
     * @mbg.generated
     */
    public Short getNavtype() {
        return navtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navType
     *
     * @param navtype the value for t_nav.navType
     *
     * @mbg.generated
     */
    public void setNavtype(Short navtype) {
        this.navtype = navtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navTitle
     *
     * @return the value of t_nav.navTitle
     *
     * @mbg.generated
     */
    public String getNavtitle() {
        return navtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navTitle
     *
     * @param navtitle the value for t_nav.navTitle
     *
     * @mbg.generated
     */
    public void setNavtitle(String navtitle) {
        this.navtitle = navtitle == null ? null : navtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navUrl
     *
     * @return the value of t_nav.navUrl
     *
     * @mbg.generated
     */
    public String getNavurl() {
        return navurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navUrl
     *
     * @param navurl the value for t_nav.navUrl
     *
     * @mbg.generated
     */
    public void setNavurl(String navurl) {
        this.navurl = navurl == null ? null : navurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navNum
     *
     * @return the value of t_nav.navNum
     *
     * @mbg.generated
     */
    public Integer getNavnum() {
        return navnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navNum
     *
     * @param navnum the value for t_nav.navNum
     *
     * @mbg.generated
     */
    public void setNavnum(Integer navnum) {
        this.navnum = navnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navLevel
     *
     * @return the value of t_nav.navLevel
     *
     * @mbg.generated
     */
    public Integer getNavlevel() {
        return navlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navLevel
     *
     * @param navlevel the value for t_nav.navLevel
     *
     * @mbg.generated
     */
    public void setNavlevel(Integer navlevel) {
        this.navlevel = navlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.navImg
     *
     * @return the value of t_nav.navImg
     *
     * @mbg.generated
     */
    public String getNavimg() {
        return navimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.navImg
     *
     * @param navimg the value for t_nav.navImg
     *
     * @mbg.generated
     */
    public void setNavimg(String navimg) {
        this.navimg = navimg == null ? null : navimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.isVisible
     *
     * @return the value of t_nav.isVisible
     *
     * @mbg.generated
     */
    public Boolean getIsvisible() {
        return isvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.isVisible
     *
     * @param isvisible the value for t_nav.isVisible
     *
     * @mbg.generated
     */
    public void setIsvisible(Boolean isvisible) {
        this.isvisible = isvisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nav.permissionTag
     *
     * @return the value of t_nav.permissionTag
     *
     * @mbg.generated
     */
    public String getPermissiontag() {
        return permissiontag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nav.permissionTag
     *
     * @param permissiontag the value for t_nav.permissionTag
     *
     * @mbg.generated
     */
    public void setPermissiontag(String permissiontag) {
        this.permissiontag = permissiontag == null ? null : permissiontag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nav
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", navid=").append(navid);
        sb.append(", cid=").append(cid);
        sb.append(", pid=").append(pid);
        sb.append(", navtype=").append(navtype);
        sb.append(", navtitle=").append(navtitle);
        sb.append(", navurl=").append(navurl);
        sb.append(", navnum=").append(navnum);
        sb.append(", navlevel=").append(navlevel);
        sb.append(", navimg=").append(navimg);
        sb.append(", isvisible=").append(isvisible);
        sb.append(", permissiontag=").append(permissiontag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}