package com.cd.rems.entity;

import java.io.Serializable;

public class TNowtype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nowType.nowTypeId
     *
     * @mbg.generated
     */
    private Integer nowtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nowType.nowType
     *
     * @mbg.generated
     */
    private String nowtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nowType
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nowType.nowTypeId
     *
     * @return the value of t_nowType.nowTypeId
     *
     * @mbg.generated
     */
    public Integer getNowtypeid() {
        return nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nowType.nowTypeId
     *
     * @param nowtypeid the value for t_nowType.nowTypeId
     *
     * @mbg.generated
     */
    public void setNowtypeid(Integer nowtypeid) {
        this.nowtypeid = nowtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nowType.nowType
     *
     * @return the value of t_nowType.nowType
     *
     * @mbg.generated
     */
    public String getNowtype() {
        return nowtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nowType.nowType
     *
     * @param nowtype the value for t_nowType.nowType
     *
     * @mbg.generated
     */
    public void setNowtype(String nowtype) {
        this.nowtype = nowtype == null ? null : nowtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nowType
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nowtypeid=").append(nowtypeid);
        sb.append(", nowtype=").append(nowtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}