package com.cd.rems.entity;

import java.io.Serializable;

public class TParklotLoan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.lotloanId
     *
     * @mbg.generated
     */
    private Integer lotloanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.parklotNum
     *
     * @mbg.generated
     */
    private String parklotnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.parkCentificateNum
     *
     * @mbg.generated
     */
    private String parkcentificatenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.loanMan
     *
     * @mbg.generated
     */
    private String loanman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.loanTel
     *
     * @mbg.generated
     */
    private String loantel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.mortgageStatus
     *
     * @mbg.generated
     */
    private Integer mortgagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.loanCycle
     *
     * @mbg.generated
     */
    private Integer loancycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.loanRate
     *
     * @mbg.generated
     */
    private Double loanrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.overdueStatus
     *
     * @mbg.generated
     */
    private Byte overduestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.overdueTimes
     *
     * @mbg.generated
     */
    private Integer overduetimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_loan.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.lotloanId
     *
     * @return the value of t_parklot_loan.lotloanId
     *
     * @mbg.generated
     */
    public Integer getLotloanid() {
        return lotloanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.lotloanId
     *
     * @param lotloanid the value for t_parklot_loan.lotloanId
     *
     * @mbg.generated
     */
    public void setLotloanid(Integer lotloanid) {
        this.lotloanid = lotloanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.parklotNum
     *
     * @return the value of t_parklot_loan.parklotNum
     *
     * @mbg.generated
     */
    public String getParklotnum() {
        return parklotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.parklotNum
     *
     * @param parklotnum the value for t_parklot_loan.parklotNum
     *
     * @mbg.generated
     */
    public void setParklotnum(String parklotnum) {
        this.parklotnum = parklotnum == null ? null : parklotnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.parkCentificateNum
     *
     * @return the value of t_parklot_loan.parkCentificateNum
     *
     * @mbg.generated
     */
    public String getParkcentificatenum() {
        return parkcentificatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.parkCentificateNum
     *
     * @param parkcentificatenum the value for t_parklot_loan.parkCentificateNum
     *
     * @mbg.generated
     */
    public void setParkcentificatenum(String parkcentificatenum) {
        this.parkcentificatenum = parkcentificatenum == null ? null : parkcentificatenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.loanMan
     *
     * @return the value of t_parklot_loan.loanMan
     *
     * @mbg.generated
     */
    public String getLoanman() {
        return loanman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.loanMan
     *
     * @param loanman the value for t_parklot_loan.loanMan
     *
     * @mbg.generated
     */
    public void setLoanman(String loanman) {
        this.loanman = loanman == null ? null : loanman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.loanTel
     *
     * @return the value of t_parklot_loan.loanTel
     *
     * @mbg.generated
     */
    public String getLoantel() {
        return loantel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.loanTel
     *
     * @param loantel the value for t_parklot_loan.loanTel
     *
     * @mbg.generated
     */
    public void setLoantel(String loantel) {
        this.loantel = loantel == null ? null : loantel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.mortgageStatus
     *
     * @return the value of t_parklot_loan.mortgageStatus
     *
     * @mbg.generated
     */
    public Integer getMortgagestatus() {
        return mortgagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.mortgageStatus
     *
     * @param mortgagestatus the value for t_parklot_loan.mortgageStatus
     *
     * @mbg.generated
     */
    public void setMortgagestatus(Integer mortgagestatus) {
        this.mortgagestatus = mortgagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.loanCycle
     *
     * @return the value of t_parklot_loan.loanCycle
     *
     * @mbg.generated
     */
    public Integer getLoancycle() {
        return loancycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.loanCycle
     *
     * @param loancycle the value for t_parklot_loan.loanCycle
     *
     * @mbg.generated
     */
    public void setLoancycle(Integer loancycle) {
        this.loancycle = loancycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.loanRate
     *
     * @return the value of t_parklot_loan.loanRate
     *
     * @mbg.generated
     */
    public Double getLoanrate() {
        return loanrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.loanRate
     *
     * @param loanrate the value for t_parklot_loan.loanRate
     *
     * @mbg.generated
     */
    public void setLoanrate(Double loanrate) {
        this.loanrate = loanrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.overdueStatus
     *
     * @return the value of t_parklot_loan.overdueStatus
     *
     * @mbg.generated
     */
    public Byte getOverduestatus() {
        return overduestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.overdueStatus
     *
     * @param overduestatus the value for t_parklot_loan.overdueStatus
     *
     * @mbg.generated
     */
    public void setOverduestatus(Byte overduestatus) {
        this.overduestatus = overduestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.overdueTimes
     *
     * @return the value of t_parklot_loan.overdueTimes
     *
     * @mbg.generated
     */
    public Integer getOverduetimes() {
        return overduetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.overdueTimes
     *
     * @param overduetimes the value for t_parklot_loan.overdueTimes
     *
     * @mbg.generated
     */
    public void setOverduetimes(Integer overduetimes) {
        this.overduetimes = overduetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_loan.carparkId
     *
     * @return the value of t_parklot_loan.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_loan.carparkId
     *
     * @param carparkid the value for t_parklot_loan.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_loan
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lotloanid=").append(lotloanid);
        sb.append(", parklotnum=").append(parklotnum);
        sb.append(", parkcentificatenum=").append(parkcentificatenum);
        sb.append(", loanman=").append(loanman);
        sb.append(", loantel=").append(loantel);
        sb.append(", mortgagestatus=").append(mortgagestatus);
        sb.append(", loancycle=").append(loancycle);
        sb.append(", loanrate=").append(loanrate);
        sb.append(", overduestatus=").append(overduestatus);
        sb.append(", overduetimes=").append(overduetimes);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}