package com.cd.rems.entity;

import java.io.Serializable;

public class TParklottypeFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotType_file.parklotTypeId
     *
     * @mbg.generated
     */
    private Integer parklottypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotType_file.parklotTypeName
     *
     * @mbg.generated
     */
    private String parklottypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotType_file.parklotType
     *
     * @mbg.generated
     */
    private Integer parklottype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotType_file.parklotTypeId
     *
     * @return the value of t_parklotType_file.parklotTypeId
     *
     * @mbg.generated
     */
    public Integer getParklottypeid() {
        return parklottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotType_file.parklotTypeId
     *
     * @param parklottypeid the value for t_parklotType_file.parklotTypeId
     *
     * @mbg.generated
     */
    public void setParklottypeid(Integer parklottypeid) {
        this.parklottypeid = parklottypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotType_file.parklotTypeName
     *
     * @return the value of t_parklotType_file.parklotTypeName
     *
     * @mbg.generated
     */
    public String getParklottypename() {
        return parklottypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotType_file.parklotTypeName
     *
     * @param parklottypename the value for t_parklotType_file.parklotTypeName
     *
     * @mbg.generated
     */
    public void setParklottypename(String parklottypename) {
        this.parklottypename = parklottypename == null ? null : parklottypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotType_file.parklotType
     *
     * @return the value of t_parklotType_file.parklotType
     *
     * @mbg.generated
     */
    public Integer getParklottype() {
        return parklottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotType_file.parklotType
     *
     * @param parklottype the value for t_parklotType_file.parklotType
     *
     * @mbg.generated
     */
    public void setParklottype(Integer parklottype) {
        this.parklottype = parklottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotType_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parklottypeid=").append(parklottypeid);
        sb.append(", parklottypename=").append(parklottypename);
        sb.append(", parklottype=").append(parklottype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}