package com.cd.rems.entity;

import java.io.Serializable;

public class TParklotMortgage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageId
     *
     * @mbg.generated
     */
    private Integer mortgageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.parklotNum
     *
     * @mbg.generated
     */
    private String parklotnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.parkCetificateNum
     *
     * @mbg.generated
     */
    private String parkcetificatenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageMan
     *
     * @mbg.generated
     */
    private String mortgageman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageTel
     *
     * @mbg.generated
     */
    private String mortgagetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageStatus
     *
     * @mbg.generated
     */
    private Integer mortgagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageCycle
     *
     * @mbg.generated
     */
    private Integer mortgagecycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.mortgageRate
     *
     * @mbg.generated
     */
    private Double mortgagerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.overdueStatus
     *
     * @mbg.generated
     */
    private Byte overduestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.overdueTimes
     *
     * @mbg.generated
     */
    private Integer overduetimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_mortgage.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageId
     *
     * @return the value of t_parklot_mortgage.mortgageId
     *
     * @mbg.generated
     */
    public Integer getMortgageid() {
        return mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageId
     *
     * @param mortgageid the value for t_parklot_mortgage.mortgageId
     *
     * @mbg.generated
     */
    public void setMortgageid(Integer mortgageid) {
        this.mortgageid = mortgageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.parklotNum
     *
     * @return the value of t_parklot_mortgage.parklotNum
     *
     * @mbg.generated
     */
    public String getParklotnum() {
        return parklotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.parklotNum
     *
     * @param parklotnum the value for t_parklot_mortgage.parklotNum
     *
     * @mbg.generated
     */
    public void setParklotnum(String parklotnum) {
        this.parklotnum = parklotnum == null ? null : parklotnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.parkCetificateNum
     *
     * @return the value of t_parklot_mortgage.parkCetificateNum
     *
     * @mbg.generated
     */
    public String getParkcetificatenum() {
        return parkcetificatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.parkCetificateNum
     *
     * @param parkcetificatenum the value for t_parklot_mortgage.parkCetificateNum
     *
     * @mbg.generated
     */
    public void setParkcetificatenum(String parkcetificatenum) {
        this.parkcetificatenum = parkcetificatenum == null ? null : parkcetificatenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageMan
     *
     * @return the value of t_parklot_mortgage.mortgageMan
     *
     * @mbg.generated
     */
    public String getMortgageman() {
        return mortgageman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageMan
     *
     * @param mortgageman the value for t_parklot_mortgage.mortgageMan
     *
     * @mbg.generated
     */
    public void setMortgageman(String mortgageman) {
        this.mortgageman = mortgageman == null ? null : mortgageman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageTel
     *
     * @return the value of t_parklot_mortgage.mortgageTel
     *
     * @mbg.generated
     */
    public String getMortgagetel() {
        return mortgagetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageTel
     *
     * @param mortgagetel the value for t_parklot_mortgage.mortgageTel
     *
     * @mbg.generated
     */
    public void setMortgagetel(String mortgagetel) {
        this.mortgagetel = mortgagetel == null ? null : mortgagetel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageStatus
     *
     * @return the value of t_parklot_mortgage.mortgageStatus
     *
     * @mbg.generated
     */
    public Integer getMortgagestatus() {
        return mortgagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageStatus
     *
     * @param mortgagestatus the value for t_parklot_mortgage.mortgageStatus
     *
     * @mbg.generated
     */
    public void setMortgagestatus(Integer mortgagestatus) {
        this.mortgagestatus = mortgagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageCycle
     *
     * @return the value of t_parklot_mortgage.mortgageCycle
     *
     * @mbg.generated
     */
    public Integer getMortgagecycle() {
        return mortgagecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageCycle
     *
     * @param mortgagecycle the value for t_parklot_mortgage.mortgageCycle
     *
     * @mbg.generated
     */
    public void setMortgagecycle(Integer mortgagecycle) {
        this.mortgagecycle = mortgagecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.mortgageRate
     *
     * @return the value of t_parklot_mortgage.mortgageRate
     *
     * @mbg.generated
     */
    public Double getMortgagerate() {
        return mortgagerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.mortgageRate
     *
     * @param mortgagerate the value for t_parklot_mortgage.mortgageRate
     *
     * @mbg.generated
     */
    public void setMortgagerate(Double mortgagerate) {
        this.mortgagerate = mortgagerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.overdueStatus
     *
     * @return the value of t_parklot_mortgage.overdueStatus
     *
     * @mbg.generated
     */
    public Byte getOverduestatus() {
        return overduestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.overdueStatus
     *
     * @param overduestatus the value for t_parklot_mortgage.overdueStatus
     *
     * @mbg.generated
     */
    public void setOverduestatus(Byte overduestatus) {
        this.overduestatus = overduestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.overdueTimes
     *
     * @return the value of t_parklot_mortgage.overdueTimes
     *
     * @mbg.generated
     */
    public Integer getOverduetimes() {
        return overduetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.overdueTimes
     *
     * @param overduetimes the value for t_parklot_mortgage.overdueTimes
     *
     * @mbg.generated
     */
    public void setOverduetimes(Integer overduetimes) {
        this.overduetimes = overduetimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_mortgage.carparkId
     *
     * @return the value of t_parklot_mortgage.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_mortgage.carparkId
     *
     * @param carparkid the value for t_parklot_mortgage.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_mortgage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mortgageid=").append(mortgageid);
        sb.append(", parklotnum=").append(parklotnum);
        sb.append(", parkcetificatenum=").append(parkcetificatenum);
        sb.append(", mortgageman=").append(mortgageman);
        sb.append(", mortgagetel=").append(mortgagetel);
        sb.append(", mortgagestatus=").append(mortgagestatus);
        sb.append(", mortgagecycle=").append(mortgagecycle);
        sb.append(", mortgagerate=").append(mortgagerate);
        sb.append(", overduestatus=").append(overduestatus);
        sb.append(", overduetimes=").append(overduetimes);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}