package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TParklot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotId
     *
     * @mbg.generated
     */
    private Integer parklotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotNum
     *
     * @mbg.generated
     */
    private String parklotnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parkCentificateNum
     *
     * @mbg.generated
     */
    private String parkcentificatenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotOwer
     *
     * @mbg.generated
     */
    private String parklotower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.owerTel
     *
     * @mbg.generated
     */
    private String owertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotValue
     *
     * @mbg.generated
     */
    private Long parklotvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.boughtPrice
     *
     * @mbg.generated
     */
    private Long boughtprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotType
     *
     * @mbg.generated
     */
    private Integer parklottype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.boughtDate
     *
     * @mbg.generated
     */
    private Date boughtdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.parklotStatus
     *
     * @mbg.generated
     */
    private Integer parklotstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotId
     *
     * @return the value of t_parklot.parklotId
     *
     * @mbg.generated
     */
    public Integer getParklotid() {
        return parklotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotId
     *
     * @param parklotid the value for t_parklot.parklotId
     *
     * @mbg.generated
     */
    public void setParklotid(Integer parklotid) {
        this.parklotid = parklotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotNum
     *
     * @return the value of t_parklot.parklotNum
     *
     * @mbg.generated
     */
    public String getParklotnum() {
        return parklotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotNum
     *
     * @param parklotnum the value for t_parklot.parklotNum
     *
     * @mbg.generated
     */
    public void setParklotnum(String parklotnum) {
        this.parklotnum = parklotnum == null ? null : parklotnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parkCentificateNum
     *
     * @return the value of t_parklot.parkCentificateNum
     *
     * @mbg.generated
     */
    public String getParkcentificatenum() {
        return parkcentificatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parkCentificateNum
     *
     * @param parkcentificatenum the value for t_parklot.parkCentificateNum
     *
     * @mbg.generated
     */
    public void setParkcentificatenum(String parkcentificatenum) {
        this.parkcentificatenum = parkcentificatenum == null ? null : parkcentificatenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotOwer
     *
     * @return the value of t_parklot.parklotOwer
     *
     * @mbg.generated
     */
    public String getParklotower() {
        return parklotower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotOwer
     *
     * @param parklotower the value for t_parklot.parklotOwer
     *
     * @mbg.generated
     */
    public void setParklotower(String parklotower) {
        this.parklotower = parklotower == null ? null : parklotower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.owerTel
     *
     * @return the value of t_parklot.owerTel
     *
     * @mbg.generated
     */
    public String getOwertel() {
        return owertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.owerTel
     *
     * @param owertel the value for t_parklot.owerTel
     *
     * @mbg.generated
     */
    public void setOwertel(String owertel) {
        this.owertel = owertel == null ? null : owertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotValue
     *
     * @return the value of t_parklot.parklotValue
     *
     * @mbg.generated
     */
    public Long getParklotvalue() {
        return parklotvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotValue
     *
     * @param parklotvalue the value for t_parklot.parklotValue
     *
     * @mbg.generated
     */
    public void setParklotvalue(Long parklotvalue) {
        this.parklotvalue = parklotvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.boughtPrice
     *
     * @return the value of t_parklot.boughtPrice
     *
     * @mbg.generated
     */
    public Long getBoughtprice() {
        return boughtprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.boughtPrice
     *
     * @param boughtprice the value for t_parklot.boughtPrice
     *
     * @mbg.generated
     */
    public void setBoughtprice(Long boughtprice) {
        this.boughtprice = boughtprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotType
     *
     * @return the value of t_parklot.parklotType
     *
     * @mbg.generated
     */
    public Integer getParklottype() {
        return parklottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotType
     *
     * @param parklottype the value for t_parklot.parklotType
     *
     * @mbg.generated
     */
    public void setParklottype(Integer parklottype) {
        this.parklottype = parklottype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.boughtDate
     *
     * @return the value of t_parklot.boughtDate
     *
     * @mbg.generated
     */
    public Date getBoughtdate() {
        return boughtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.boughtDate
     *
     * @param boughtdate the value for t_parklot.boughtDate
     *
     * @mbg.generated
     */
    public void setBoughtdate(Date boughtdate) {
        this.boughtdate = boughtdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.parklotStatus
     *
     * @return the value of t_parklot.parklotStatus
     *
     * @mbg.generated
     */
    public Integer getParklotstatus() {
        return parklotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.parklotStatus
     *
     * @param parklotstatus the value for t_parklot.parklotStatus
     *
     * @mbg.generated
     */
    public void setParklotstatus(Integer parklotstatus) {
        this.parklotstatus = parklotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot.carparkId
     *
     * @return the value of t_parklot.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot.carparkId
     *
     * @param carparkid the value for t_parklot.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parklotid=").append(parklotid);
        sb.append(", parklotnum=").append(parklotnum);
        sb.append(", parkcentificatenum=").append(parkcentificatenum);
        sb.append(", parklotower=").append(parklotower);
        sb.append(", owertel=").append(owertel);
        sb.append(", parklotvalue=").append(parklotvalue);
        sb.append(", boughtprice=").append(boughtprice);
        sb.append(", parklottype=").append(parklottype);
        sb.append(", boughtdate=").append(boughtdate);
        sb.append(", parklotstatus=").append(parklotstatus);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}