package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TParklotLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.lotlogId
     *
     * @mbg.generated
     */
    private Integer lotlogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.parklotNum
     *
     * @mbg.generated
     */
    private String parklotnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.parkCentificateNum
     *
     * @mbg.generated
     */
    private String parkcentificatenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.changeStatus
     *
     * @mbg.generated
     */
    private Integer changestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.changeDate
     *
     * @mbg.generated
     */
    private Date changedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.changeContent
     *
     * @mbg.generated
     */
    private String changecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.changeNote
     *
     * @mbg.generated
     */
    private String changenote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_log.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.lotlogId
     *
     * @return the value of t_parklot_log.lotlogId
     *
     * @mbg.generated
     */
    public Integer getLotlogid() {
        return lotlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.lotlogId
     *
     * @param lotlogid the value for t_parklot_log.lotlogId
     *
     * @mbg.generated
     */
    public void setLotlogid(Integer lotlogid) {
        this.lotlogid = lotlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.parklotNum
     *
     * @return the value of t_parklot_log.parklotNum
     *
     * @mbg.generated
     */
    public String getParklotnum() {
        return parklotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.parklotNum
     *
     * @param parklotnum the value for t_parklot_log.parklotNum
     *
     * @mbg.generated
     */
    public void setParklotnum(String parklotnum) {
        this.parklotnum = parklotnum == null ? null : parklotnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.parkCentificateNum
     *
     * @return the value of t_parklot_log.parkCentificateNum
     *
     * @mbg.generated
     */
    public String getParkcentificatenum() {
        return parkcentificatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.parkCentificateNum
     *
     * @param parkcentificatenum the value for t_parklot_log.parkCentificateNum
     *
     * @mbg.generated
     */
    public void setParkcentificatenum(String parkcentificatenum) {
        this.parkcentificatenum = parkcentificatenum == null ? null : parkcentificatenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.changeStatus
     *
     * @return the value of t_parklot_log.changeStatus
     *
     * @mbg.generated
     */
    public Integer getChangestatus() {
        return changestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.changeStatus
     *
     * @param changestatus the value for t_parklot_log.changeStatus
     *
     * @mbg.generated
     */
    public void setChangestatus(Integer changestatus) {
        this.changestatus = changestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.changeDate
     *
     * @return the value of t_parklot_log.changeDate
     *
     * @mbg.generated
     */
    public Date getChangedate() {
        return changedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.changeDate
     *
     * @param changedate the value for t_parklot_log.changeDate
     *
     * @mbg.generated
     */
    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.changeContent
     *
     * @return the value of t_parklot_log.changeContent
     *
     * @mbg.generated
     */
    public String getChangecontent() {
        return changecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.changeContent
     *
     * @param changecontent the value for t_parklot_log.changeContent
     *
     * @mbg.generated
     */
    public void setChangecontent(String changecontent) {
        this.changecontent = changecontent == null ? null : changecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.changeNote
     *
     * @return the value of t_parklot_log.changeNote
     *
     * @mbg.generated
     */
    public String getChangenote() {
        return changenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.changeNote
     *
     * @param changenote the value for t_parklot_log.changeNote
     *
     * @mbg.generated
     */
    public void setChangenote(String changenote) {
        this.changenote = changenote == null ? null : changenote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_log.carparkId
     *
     * @return the value of t_parklot_log.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_log.carparkId
     *
     * @param carparkid the value for t_parklot_log.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lotlogid=").append(lotlogid);
        sb.append(", parklotnum=").append(parklotnum);
        sb.append(", parkcentificatenum=").append(parkcentificatenum);
        sb.append(", changestatus=").append(changestatus);
        sb.append(", changedate=").append(changedate);
        sb.append(", changecontent=").append(changecontent);
        sb.append(", changenote=").append(changenote);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}