package com.cd.rems.entity;

import java.io.Serializable;

public class TParklotstatusFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotStatus_file.parklotStatusId
     *
     * @mbg.generated
     */
    private Integer parklotstatusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotStatus_file.parklotStatusName
     *
     * @mbg.generated
     */
    private String parklotstatusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklotStatus_file.parklotStatus
     *
     * @mbg.generated
     */
    private Integer parklotstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotStatus_file.parklotStatusId
     *
     * @return the value of t_parklotStatus_file.parklotStatusId
     *
     * @mbg.generated
     */
    public Integer getParklotstatusid() {
        return parklotstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotStatus_file.parklotStatusId
     *
     * @param parklotstatusid the value for t_parklotStatus_file.parklotStatusId
     *
     * @mbg.generated
     */
    public void setParklotstatusid(Integer parklotstatusid) {
        this.parklotstatusid = parklotstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotStatus_file.parklotStatusName
     *
     * @return the value of t_parklotStatus_file.parklotStatusName
     *
     * @mbg.generated
     */
    public String getParklotstatusname() {
        return parklotstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotStatus_file.parklotStatusName
     *
     * @param parklotstatusname the value for t_parklotStatus_file.parklotStatusName
     *
     * @mbg.generated
     */
    public void setParklotstatusname(String parklotstatusname) {
        this.parklotstatusname = parklotstatusname == null ? null : parklotstatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklotStatus_file.parklotStatus
     *
     * @return the value of t_parklotStatus_file.parklotStatus
     *
     * @mbg.generated
     */
    public Integer getParklotstatus() {
        return parklotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklotStatus_file.parklotStatus
     *
     * @param parklotstatus the value for t_parklotStatus_file.parklotStatus
     *
     * @mbg.generated
     */
    public void setParklotstatus(Integer parklotstatus) {
        this.parklotstatus = parklotstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklotStatus_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parklotstatusid=").append(parklotstatusid);
        sb.append(", parklotstatusname=").append(parklotstatusname);
        sb.append(", parklotstatus=").append(parklotstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}