package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TParklotMonthrent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentId
     *
     * @mbg.generated
     */
    private Integer rentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.parklotNum
     *
     * @mbg.generated
     */
    private String parklotnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.parkCentificateNum
     *
     * @mbg.generated
     */
    private String parkcentificatenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.renter
     *
     * @mbg.generated
     */
    private String renter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.renterTel
     *
     * @mbg.generated
     */
    private String rentertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.renterAddress
     *
     * @mbg.generated
     */
    private String renteraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentStartDate
     *
     * @mbg.generated
     */
    private Date rentstartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentEndDate
     *
     * @mbg.generated
     */
    private Date rentenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentType
     *
     * @mbg.generated
     */
    private Integer renttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentCycle
     *
     * @mbg.generated
     */
    private Integer rentcycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentUnitprice
     *
     * @mbg.generated
     */
    private Long rentunitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.rentCarnum
     *
     * @mbg.generated
     */
    private String rentcarnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parklot_monthrent.carparkId
     *
     * @mbg.generated
     */
    private Integer carparkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_parklot_monthrent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentId
     *
     * @return the value of t_parklot_monthrent.rentId
     *
     * @mbg.generated
     */
    public Integer getRentid() {
        return rentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentId
     *
     * @param rentid the value for t_parklot_monthrent.rentId
     *
     * @mbg.generated
     */
    public void setRentid(Integer rentid) {
        this.rentid = rentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.parklotNum
     *
     * @return the value of t_parklot_monthrent.parklotNum
     *
     * @mbg.generated
     */
    public String getParklotnum() {
        return parklotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.parklotNum
     *
     * @param parklotnum the value for t_parklot_monthrent.parklotNum
     *
     * @mbg.generated
     */
    public void setParklotnum(String parklotnum) {
        this.parklotnum = parklotnum == null ? null : parklotnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.parkCentificateNum
     *
     * @return the value of t_parklot_monthrent.parkCentificateNum
     *
     * @mbg.generated
     */
    public String getParkcentificatenum() {
        return parkcentificatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.parkCentificateNum
     *
     * @param parkcentificatenum the value for t_parklot_monthrent.parkCentificateNum
     *
     * @mbg.generated
     */
    public void setParkcentificatenum(String parkcentificatenum) {
        this.parkcentificatenum = parkcentificatenum == null ? null : parkcentificatenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.renter
     *
     * @return the value of t_parklot_monthrent.renter
     *
     * @mbg.generated
     */
    public String getRenter() {
        return renter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.renter
     *
     * @param renter the value for t_parklot_monthrent.renter
     *
     * @mbg.generated
     */
    public void setRenter(String renter) {
        this.renter = renter == null ? null : renter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.renterTel
     *
     * @return the value of t_parklot_monthrent.renterTel
     *
     * @mbg.generated
     */
    public String getRentertel() {
        return rentertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.renterTel
     *
     * @param rentertel the value for t_parklot_monthrent.renterTel
     *
     * @mbg.generated
     */
    public void setRentertel(String rentertel) {
        this.rentertel = rentertel == null ? null : rentertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.renterAddress
     *
     * @return the value of t_parklot_monthrent.renterAddress
     *
     * @mbg.generated
     */
    public String getRenteraddress() {
        return renteraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.renterAddress
     *
     * @param renteraddress the value for t_parklot_monthrent.renterAddress
     *
     * @mbg.generated
     */
    public void setRenteraddress(String renteraddress) {
        this.renteraddress = renteraddress == null ? null : renteraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentStartDate
     *
     * @return the value of t_parklot_monthrent.rentStartDate
     *
     * @mbg.generated
     */
    public Date getRentstartdate() {
        return rentstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentStartDate
     *
     * @param rentstartdate the value for t_parklot_monthrent.rentStartDate
     *
     * @mbg.generated
     */
    public void setRentstartdate(Date rentstartdate) {
        this.rentstartdate = rentstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentEndDate
     *
     * @return the value of t_parklot_monthrent.rentEndDate
     *
     * @mbg.generated
     */
    public Date getRentenddate() {
        return rentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentEndDate
     *
     * @param rentenddate the value for t_parklot_monthrent.rentEndDate
     *
     * @mbg.generated
     */
    public void setRentenddate(Date rentenddate) {
        this.rentenddate = rentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentType
     *
     * @return the value of t_parklot_monthrent.rentType
     *
     * @mbg.generated
     */
    public Integer getRenttype() {
        return renttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentType
     *
     * @param renttype the value for t_parklot_monthrent.rentType
     *
     * @mbg.generated
     */
    public void setRenttype(Integer renttype) {
        this.renttype = renttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentCycle
     *
     * @return the value of t_parklot_monthrent.rentCycle
     *
     * @mbg.generated
     */
    public Integer getRentcycle() {
        return rentcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentCycle
     *
     * @param rentcycle the value for t_parklot_monthrent.rentCycle
     *
     * @mbg.generated
     */
    public void setRentcycle(Integer rentcycle) {
        this.rentcycle = rentcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentUnitprice
     *
     * @return the value of t_parklot_monthrent.rentUnitprice
     *
     * @mbg.generated
     */
    public Long getRentunitprice() {
        return rentunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentUnitprice
     *
     * @param rentunitprice the value for t_parklot_monthrent.rentUnitprice
     *
     * @mbg.generated
     */
    public void setRentunitprice(Long rentunitprice) {
        this.rentunitprice = rentunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.rentCarnum
     *
     * @return the value of t_parklot_monthrent.rentCarnum
     *
     * @mbg.generated
     */
    public String getRentcarnum() {
        return rentcarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.rentCarnum
     *
     * @param rentcarnum the value for t_parklot_monthrent.rentCarnum
     *
     * @mbg.generated
     */
    public void setRentcarnum(String rentcarnum) {
        this.rentcarnum = rentcarnum == null ? null : rentcarnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parklot_monthrent.carparkId
     *
     * @return the value of t_parklot_monthrent.carparkId
     *
     * @mbg.generated
     */
    public Integer getCarparkid() {
        return carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parklot_monthrent.carparkId
     *
     * @param carparkid the value for t_parklot_monthrent.carparkId
     *
     * @mbg.generated
     */
    public void setCarparkid(Integer carparkid) {
        this.carparkid = carparkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parklot_monthrent
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rentid=").append(rentid);
        sb.append(", parklotnum=").append(parklotnum);
        sb.append(", parkcentificatenum=").append(parkcentificatenum);
        sb.append(", renter=").append(renter);
        sb.append(", rentertel=").append(rentertel);
        sb.append(", renteraddress=").append(renteraddress);
        sb.append(", rentstartdate=").append(rentstartdate);
        sb.append(", rentenddate=").append(rentenddate);
        sb.append(", renttype=").append(renttype);
        sb.append(", rentcycle=").append(rentcycle);
        sb.append(", rentunitprice=").append(rentunitprice);
        sb.append(", rentcarnum=").append(rentcarnum);
        sb.append(", carparkid=").append(carparkid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}