package com.cd.rems.entity;

import java.io.Serializable;

public class TRenttypeFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rentType_file.rentTypeId
     *
     * @mbg.generated
     */
    private Integer renttypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rentType_file.rentTypeName
     *
     * @mbg.generated
     */
    private String renttypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rentType_file.rentType
     *
     * @mbg.generated
     */
    private Integer renttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rentType_file.rentTypeId
     *
     * @return the value of t_rentType_file.rentTypeId
     *
     * @mbg.generated
     */
    public Integer getRenttypeid() {
        return renttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rentType_file.rentTypeId
     *
     * @param renttypeid the value for t_rentType_file.rentTypeId
     *
     * @mbg.generated
     */
    public void setRenttypeid(Integer renttypeid) {
        this.renttypeid = renttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rentType_file.rentTypeName
     *
     * @return the value of t_rentType_file.rentTypeName
     *
     * @mbg.generated
     */
    public String getRenttypename() {
        return renttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rentType_file.rentTypeName
     *
     * @param renttypename the value for t_rentType_file.rentTypeName
     *
     * @mbg.generated
     */
    public void setRenttypename(String renttypename) {
        this.renttypename = renttypename == null ? null : renttypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rentType_file.rentType
     *
     * @return the value of t_rentType_file.rentType
     *
     * @mbg.generated
     */
    public Integer getRenttype() {
        return renttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rentType_file.rentType
     *
     * @param renttype the value for t_rentType_file.rentType
     *
     * @mbg.generated
     */
    public void setRenttype(Integer renttype) {
        this.renttype = renttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rentType_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", renttypeid=").append(renttypeid);
        sb.append(", renttypename=").append(renttypename);
        sb.append(", renttype=").append(renttype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}