package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roleId
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roleName
     *
     * @mbg.generated
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roleDescrib
     *
     * @mbg.generated
     */
    private String roledescrib;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.addedDate
     *
     * @mbg.generated
     */
    private Date addeddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.roleId
     *
     * @return the value of t_role.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.roleId
     *
     * @param roleid the value for t_role.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.roleName
     *
     * @return the value of t_role.roleName
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.roleName
     *
     * @param rolename the value for t_role.roleName
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.roleDescrib
     *
     * @return the value of t_role.roleDescrib
     *
     * @mbg.generated
     */
    public String getRoledescrib() {
        return roledescrib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.roleDescrib
     *
     * @param roledescrib the value for t_role.roleDescrib
     *
     * @mbg.generated
     */
    public void setRoledescrib(String roledescrib) {
        this.roledescrib = roledescrib == null ? null : roledescrib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.addedDate
     *
     * @return the value of t_role.addedDate
     *
     * @mbg.generated
     */
    public Date getAddeddate() {
        return addeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.addedDate
     *
     * @param addeddate the value for t_role.addedDate
     *
     * @mbg.generated
     */
    public void setAddeddate(Date addeddate) {
        this.addeddate = addeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", rolename=").append(rolename);
        sb.append(", roledescrib=").append(roledescrib);
        sb.append(", addeddate=").append(addeddate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}