package com.cd.rems.entity;

import java.io.Serializable;
import java.util.Date;

public class TShops implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.shopsId
     *
     * @mbg.generated
     */
    private Integer shopsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.deliveredDate
     *
     * @mbg.generated
     */
    private Date delivereddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.shopsTotalArea
     *
     * @mbg.generated
     */
    private Long shopstotalarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.shopsNumber
     *
     * @mbg.generated
     */
    private Integer shopsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.averagePrice
     *
     * @mbg.generated
     */
    private Long averageprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shops.buildingId
     *
     * @mbg.generated
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shops
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.shopsId
     *
     * @return the value of t_shops.shopsId
     *
     * @mbg.generated
     */
    public Integer getShopsid() {
        return shopsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.shopsId
     *
     * @param shopsid the value for t_shops.shopsId
     *
     * @mbg.generated
     */
    public void setShopsid(Integer shopsid) {
        this.shopsid = shopsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.deliveredDate
     *
     * @return the value of t_shops.deliveredDate
     *
     * @mbg.generated
     */
    public Date getDelivereddate() {
        return delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.deliveredDate
     *
     * @param delivereddate the value for t_shops.deliveredDate
     *
     * @mbg.generated
     */
    public void setDelivereddate(Date delivereddate) {
        this.delivereddate = delivereddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.shopsTotalArea
     *
     * @return the value of t_shops.shopsTotalArea
     *
     * @mbg.generated
     */
    public Long getShopstotalarea() {
        return shopstotalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.shopsTotalArea
     *
     * @param shopstotalarea the value for t_shops.shopsTotalArea
     *
     * @mbg.generated
     */
    public void setShopstotalarea(Long shopstotalarea) {
        this.shopstotalarea = shopstotalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.shopsNumber
     *
     * @return the value of t_shops.shopsNumber
     *
     * @mbg.generated
     */
    public Integer getShopsnumber() {
        return shopsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.shopsNumber
     *
     * @param shopsnumber the value for t_shops.shopsNumber
     *
     * @mbg.generated
     */
    public void setShopsnumber(Integer shopsnumber) {
        this.shopsnumber = shopsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.averagePrice
     *
     * @return the value of t_shops.averagePrice
     *
     * @mbg.generated
     */
    public Long getAverageprice() {
        return averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.averagePrice
     *
     * @param averageprice the value for t_shops.averagePrice
     *
     * @mbg.generated
     */
    public void setAverageprice(Long averageprice) {
        this.averageprice = averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shops.buildingId
     *
     * @return the value of t_shops.buildingId
     *
     * @mbg.generated
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shops.buildingId
     *
     * @param buildingid the value for t_shops.buildingId
     *
     * @mbg.generated
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shops
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopsid=").append(shopsid);
        sb.append(", delivereddate=").append(delivereddate);
        sb.append(", shopstotalarea=").append(shopstotalarea);
        sb.append(", shopsnumber=").append(shopsnumber);
        sb.append(", averageprice=").append(averageprice);
        sb.append(", buildingid=").append(buildingid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}