package com.cd.rems.entity;

import java.io.Serializable;

public class TWlantype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_WLANType.WLANTypeId
     *
     * @mbg.generated
     */
    private Integer wlantypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_WLANType.WLANType
     *
     * @mbg.generated
     */
    private String wlantype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_WLANType.isSelected
     *
     * @mbg.generated
     */
    private Boolean isselected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_WLANType.carparkDeviceId
     *
     * @mbg.generated
     */
    private Integer carparkdeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_WLANType
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_WLANType.WLANTypeId
     *
     * @return the value of t_WLANType.WLANTypeId
     *
     * @mbg.generated
     */
    public Integer getWlantypeid() {
        return wlantypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_WLANType.WLANTypeId
     *
     * @param wlantypeid the value for t_WLANType.WLANTypeId
     *
     * @mbg.generated
     */
    public void setWlantypeid(Integer wlantypeid) {
        this.wlantypeid = wlantypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_WLANType.WLANType
     *
     * @return the value of t_WLANType.WLANType
     *
     * @mbg.generated
     */
    public String getWlantype() {
        return wlantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_WLANType.WLANType
     *
     * @param wlantype the value for t_WLANType.WLANType
     *
     * @mbg.generated
     */
    public void setWlantype(String wlantype) {
        this.wlantype = wlantype == null ? null : wlantype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_WLANType.isSelected
     *
     * @return the value of t_WLANType.isSelected
     *
     * @mbg.generated
     */
    public Boolean getIsselected() {
        return isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_WLANType.isSelected
     *
     * @param isselected the value for t_WLANType.isSelected
     *
     * @mbg.generated
     */
    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_WLANType.carparkDeviceId
     *
     * @return the value of t_WLANType.carparkDeviceId
     *
     * @mbg.generated
     */
    public Integer getCarparkdeviceid() {
        return carparkdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_WLANType.carparkDeviceId
     *
     * @param carparkdeviceid the value for t_WLANType.carparkDeviceId
     *
     * @mbg.generated
     */
    public void setCarparkdeviceid(Integer carparkdeviceid) {
        this.carparkdeviceid = carparkdeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_WLANType
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wlantypeid=").append(wlantypeid);
        sb.append(", wlantype=").append(wlantype);
        sb.append(", isselected=").append(isselected);
        sb.append(", carparkdeviceid=").append(carparkdeviceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}